### ISSUE TITLE
rstudiapi typo should be corrected into rstudioapi

### ISSUE THREAD

**Issue by alessap** [lorenzwalthert/precommit#102]
I encountered the following error when using ```precommit``` within RStudio and I believe it is simply a typo:

```> precommit::use_precommit()
pre-commit installed at .git/hooks/pre-commit
✔ Sucessfully installed pre-commit for this repo.
● Edit .precommit-hooks.yaml to (de)activate the hooks you want to use.
  All available hooks:
  https://pre-commit.com/hooks.html
  R specific hooks:
  https://github.com/lorenzwalthert/precommit.
Updating https://github.com/lorenzwalthert/precommit ... already up to date.
Updating https://github.com/pre-commit/pre-commit-hooks ... already up to date.
✔ Ran `pre-commit autoupdate` to get the latest version of the hooks.
Error in loadNamespace(name) : there is no package called ‘rstudiapi’
```

```rstudiapi``` package does not exist. It should have been spelled ```rstudioapi```

**Comment by alessap** [comment]
I have made a pull request here: [https://github.com/lorenzwalthert/precommit/pull/103](https://github.com/lorenzwalthert/precommit/pull/103)

**Comment by lorenzwalthert** [comment]
Dang. And thanks. We should add a test for `ude_precommit()` soon.

**Comment by alessap** [comment]
Thank you for your repo: I come from the Python world and only recently I started working with R. I was very happy to find your repo and use precommit with R. 

Sure, I am happy to help! :-)

**Comment by lorenzwalthert** [comment]
The typo was just introduced with #101 just yesterday with #101. I added a test in 12996ec.
