### ISSUE TITLE
Updating changelog

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#108]
User wish: Be more verbose with NEWS of this project, even if its in development. I am checking constantly and having a hard time tracking what has changed - latest entry in https://lorenzwalthert.github.io/precommit/news/index.html is from v0.9017.

**Comment by lorenzwalthert** [comment]
Right... I guess I should stop pushing to master :hushed:. And then in every PR, update NEWS. Once we'll get to the first CRAN release, we'll have other standards, but I can try to abide by them asap.

**Comment by lorenzwalthert** [comment]
I have been doing this some time now and plan to continue.
