### ISSUE TITLE
Create r-reticulate conda environment if missing

### ISSUE THREAD

**Issue by fschoner** [lorenzwalthert/precommit#116]
So far, 
`remotes::install_github("lorenzwalthert/precommit")` 
does not create an r-reticulate conda environment that is needed to run 
`precommit::install_precommit()`.

**Comment by lorenzwalthert** [comment]
Thanks @fschoner, I track this in #113 and the respecting PR (#114) will be merged very soon.

**Comment by lorenzwalthert** [comment]
Do you have the latest version from GitHub?

**Comment by fschoner** [comment]
@lorenzwalthert sorry. Uninstalled and then re-installed it - works fine now! Thanks!

**Comment by lorenzwalthert** [comment]
Great, I am closing this then.
