### ISSUE TITLE
Difficult-to-parse fatal error in precommit setup

### ISSUE THREAD

**Issue by mikekaminsky** [lorenzwalthert/precommit#135]
Hi 👋 

I'm trying to get `precommit` setup and have been following the instructions in the readme.

I attempt to run

```
> precommit::use_precommit()
```

And I get the following error (I've included the `last_error()` and `last_trace()` for good measure).

I'm not even sure where to start for debugging this -- any help would be much appreciated!

```
> precommit::use_precommit()
ℹ Using local conifig from /Users/michaelkaminsky/workspace/recast/recast/renv/library/R-3.6/x86_64-apple-darwin19.0.0/precommit/pre-commit-config.yaml.
Error: Error during initialization:
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error during initialization:
Backtrace:
 1. precommit::use_precommit()
 2. precommit:::install_repo(path_root)
 3. withr::with_dir(...)
 4. base::force(code)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Error during initialization:
Backtrace:
    █
 1. └─precommit::use_precommit()
 2.   └─precommit:::install_repo(path_root)
 3.     └─withr::with_dir(...)
 4.       └─base::force(code)
```

**Comment by lorenzwalthert** [comment]
Thanks @mikekaminsky. Can you tell me

- Which installation method you chose.
- What `precommit::path_precommit_exec()` returns.

**Comment by mikekaminsky** [comment]
@lorenzwalthert 

* I installed with homebrew
* ``` precommit::path_precommit_exec() [1] "/usr/local/bin/pre-commit"```
* Using macOS

Definitely could be an `renv` issue! I haven't dug into the code here enough to see how the libraries link together. I'll take a look at that first.

**Comment by mikekaminsky** [comment]
For good measure I also experimented with setting the `path_root` argument to be the local directory (`path_root='./'`) but had no luck with that either

**Comment by lorenzwalthert** [comment]
Ok, thanks. I just tried in a renv project and it also worked, on macOS, with home-brew. Your command `precommit::use_precommit()` command fails here: `system2(precommit::path_precommit_exec(),"install", ...)` and output is captured. Can you try this in your R console and post the output here? 

When did you download {precommit} from GitHub? Can you try with the latest version: It should give a more informative error message for `precommit::use_precommit()`.

**Comment by mikekaminsky** [comment]
```> devtools::install_github('lorenzwalthert/precommit')
Using github PAT from envvar GITHUB_PAT
Skipping install of 'precommit' from a github remote, the SHA1 (dc75825e) has not changed since last install.
```

AHA!

```
> system2(precommit::path_precommit_exec(),"install")
[ERROR] Cowardly refusing to install hooks with `core.hooksPath` set.
hint: `git config --unset-all core.hooksPath`
```

That's the issue right there. I had set up some hooks manually and so (clearly) that blocks install. I'll unset that and I fell confident this will start working

**Comment by lorenzwalthert** [comment]
Can you, before you do that, run `precommit::use_precommit()` so I can check the output?

**Comment by mikekaminsky** [comment]
Unfortunately that output hasn't changed

```
> precommit::use_precommit()
ℹ Using local conifig from /Users/michaelkaminsky/workspace/recast/recast/renv/library/R-3.6/x86_64-apple-darwin19.0.0/precommit/pre-commit-config.yaml.
Error: Error during initialization:
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by lorenzwalthert** [comment]
oh I might not have pushed it sorry. One second.

**Comment by lorenzwalthert** [comment]
Now it's there in 1fe5b08.

**Comment by mikekaminsky** [comment]
Much better!

```
> precommit::use_precommit()
ℹ Using local conifig from /Users/michaelkaminsky/workspace/recast/recast/renv/library/R-3.6/x86_64-apple-darwin19.0.0/precommit/pre-commit-config.yaml.
✖ Failed to install pre-commit for repo recast.
Error: Problems during initialization:
stderr: [ERROR] Cowardly refusing to install hooks with `core.hooksPath` set.

stdout:none
* Problems during initialization:
stderr: hint: `git config --unset-all core.hooksPath`

stdout:none
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by lorenzwalthert** [comment]
Ok, I'll remove "none" and then it's better. Thanks for submitting the issue.

**Comment by lorenzwalthert** [comment]
I wonder if we should detect hooks installed in a repo already and warn the user. Or leave this to pre-commit. Not even sure where this error message is coming from (git or precommit).

**Comment by mikekaminsky** [comment]
Thanks for jumping on this so quickly @lorenzwalthert.

With this error message it's at least clear where the problem is coming from. You could put a note in the setup section of the README indicating that pre-existing hooks will cause issues but 🤷‍♀

**Comment by mikekaminsky** [comment]
This error doesn't read like a `git` error so I'd guess it's coming from pre-comit:
```[ERROR] Cowardly refusing to install hooks with `core.hooksPath` set.```

**Comment by lorenzwalthert** [comment]
Can you try again with the master branch? Sorry I can't reproduce easily.

**Comment by mikekaminsky** [comment]
```> precommit::use_precommit()
ℹ Using local conifig from /Users/michaelkaminsky/workspace/recast/recast/renv/library/R-3.6/x86_64-apple-darwin19.0.0/precommit/pre-commit-config.yaml.
✖ Failed to install pre-commit for repo recast.
Error: Problems during initialization:
stderr:

stdout:[ERROR] Cowardly refusing to install hooks with `core.hooksPath` set.
hint: `git config --unset-all core.hooksPath`
Run `rlang::last_error()` to see where the error occurred.
```

Also FYI I can reproduce this easily just by running `git config core.hooksPath .githooks` and then restarting R

**Comment by lorenzwalthert** [comment]
Related: https://github.com/pre-commit/pre-commit/issues/1298.

**Comment by lorenzwalthert** [comment]
What are the implications of unsetting? Did you have some hooks defined in a different directory than `hooks`? Just wondering how this can be relevant for other users.

**Comment by mikekaminsky** [comment]
Yeah, so I had put a hook in the top-level of the directory (to keep it in version control). So this unsets that. (I think...)
