### ISSUE TITLE
devtools::check()

### ISSUE THREAD

**Issue by hrbrmstr** [lorenzwalthert/precommit#15]
I'd be willing to de-hackify my personal hook that does a pre-commit CRAN check on a pkg repo to prevent sending an un-checkable change up (with all the cascade failures that result)

**Comment by lorenzwalthert** [comment]
Interesting. I thought about implementing `devtools::check()` and similar too but I figured it would take way too long to run that as a pre-commit hook. What am I missing? Which file types would trigger the hook?

**Comment by hrbrmstr** [comment]
No, i do a full-on check in ~recent and all new packages.

tis toggle-able when i know i'm just making a small change.

**Comment by lorenzwalthert** [comment]
Ok. Well I wondered for some time if there are no efforts to:

- parallelize `R CMD` check.
- cache R cmd check results so not all parts have to be re-run every time.

Anyways, I guess that's a different issue. I am happy to review a PR on your the initial proposal. You can find some guidance about the repo and how to approach things in the `CONTRIBUTING.md`. Note that #16 has introduced some structural changes a few minutes ago (moved tests into test/testthat), so better rebase on upstream master.

**Comment by lorenzwalthert** [comment]
I am no longer open to adding a `R cmd check` hook to this repo. @hrbrmstr if you want to implement this, you can still do so as a local hook as described [here](https://pre-commit.com/#repository-local-hooks) or check out some local hooks are implemented in this repo.
