### ISSUE TITLE
Allow to pass --install-hooks parameter to installation process.

### ISSUE THREAD

**Issue by krzyslom** [lorenzwalthert/precommit#158]
I'm trying to fully automate the project repository setup. I have reticulate 1.15, its miniconda installation, and precommit 0.0.0.9044 on board. After running the following steps:

1. create new git repo project
1. ` precommit::use_precommit()`
1. `git add -A`
1. `git commit -m "Initial commit"`

just before the hooks are executed the environment for them has to be installed. This is manifested by the following message inside the RStudio's terminal:
```sh
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

Changing [this line](https://github.com/lorenzwalthert/precommit/blob/a00bbd867b8abd67702e0ac81f90ad2ea2e35584/R/install.R#L49) to
```R
out <- call_precommit("install", "--install-hooks")
```
and moving [repo installation](https://github.com/lorenzwalthert/precommit/blob/a00bbd867b8abd67702e0ac81f90ad2ea2e35584/R/setup.R#L31) after `autoupdate` call (`--install-hooks` works only if the config yaml file is already present) removes this step from the end user's experience, since [--install-hooks](https://pre-commit.com/#pre-commit-install) installs environments for all of the available hooks in advance.

Alternatively the `--install-hooks` call could be hardcoded.

I could provide a proper PR if this gets green light.

**Comment by lorenzwalthert** [comment]
Sure, we can improve this, thanks for the suggestion. I am happy to review a PR if you expose `install_repo` in `precommit::use_precommit()` as the second argument with default to `TRUE` like this: 

```r
use_precommit(
  config_source = getOption("precommit.config_source"),
  install_repo = TRUE,
  force = FALSE,
  open = rstudioapi::isAvailable(),
  root = here::here()
)
```

I think I chose `install_repo` and `install_system` initially in the source code to make it clear which installation we are referring to (and I think `install_hooks` is ambiguous). What do you think of the API change?
