### ISSUE TITLE
Error when committing

### ISSUE THREAD

**Issue by fschoner** [lorenzwalthert/precommit#169]
After updating to R 4.0, I keep receiving the following error when trying to commit

style-files..............................................................Failed
- hook id: style-files
- exit code: 1
Fehler in loadNamespace(name) : es gibt kein Paket namens 'docopt'
Ruft auf: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Ausführung angehalten

lintr....................................................................Failed
- hook id: lintr
- exit code: 1

Fehler in loadNamespace(name) : es gibt kein Paket namens 'docopt'
Ruft auf: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Ausführung angehalten

This occurs even though I have installed docopt on all
` .libPaths()`
Any idea what goes wrong?

**Comment by lorenzwalthert** [comment]
Well, as you described and as described in the README, `install.packages('docopt')` should do. Try removing and re-installing? Did dyou set `.libPaths()` in `.Rprofile`?

**Comment by fschoner** [comment]
Did not help. No, I did not set `.libPaths()` in `.Rprofile`

**Comment by lorenzwalthert** [comment]
So the hooks runs [this](https://github.com/lorenzwalthert/precommit/blob/master/inst/bin/style-files) script. Can you download, put it in your working directory and run 
```bash
chmod 744 style-files
./style-files file1.R
```
where `file1.R` is the path to an R file to style?

**Comment by lorenzwalthert** [comment]
You can also use `pre-commit try-repo` when you cloned {precommit}, edit the script and run the hook interactively as described [here](https://pre-commit.com/#developing-hooks-interactively).

**Comment by fschoner** [comment]
Fixed it. I didn't have the most recent version of precommit in the environment file.

**Comment by lorenzwalthert** [comment]
Which file?

**Comment by fschoner** [comment]
My own environment.yml.

**Comment by lorenzwalthert** [comment]
the one for `conda`?

**Comment by fschoner** [comment]
Yes

**Comment by lorenzwalthert** [comment]
Ok. I don't see how this is related but we can close the issue anyways.
