### ISSUE TITLE
Hook "use-tidy-description":  False positive alert?

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#181]
The hook fails for me in a repo.
However, the repo DESC is up-to-date and running `usethis::use_tidy_description()` does not change anything in DESCR.

Did you experience this in practice in the past?

**Comment by lorenzwalthert** [comment]
I assume you staged DESCRIPTION?

**Comment by lorenzwalthert** [comment]
Sometimes RStudio hangs after you attempted to commit previously and pre-commit made it fail. Can you restart the IDE?

**Comment by pat-s** [comment]
It does not matter whether DESC is staged or not (i.e. up-to-date), the hook always fails.

Same issue via CLI. Even after removing precommit and initializing it again.

```yml
# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.2
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=mlr_style]
    -   id: roxygenize
    # codemeta must be above use-tidy-description when both are used
    # -   id: codemeta-description-updated
    -   id: use-tidy-description
    -   id: spell-check
        exclude: >
          (?x)^(
          data/.*|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData
          )$
    -   id: lintr
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: deps-in-desc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: '\.Rd'
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
```

**Comment by lorenzwalthert** [comment]
Can you create a reprex / point me to the git repo where you find this problem?

**Comment by pat-s** [comment]
Had this in all repos today, hence I assume its not repo related but more os-specific?

Here is one of today: https://github.com/mlr-org/mlr3verse

**Comment by lorenzwalthert** [comment]
reprex: 

1. clone `mlr-or/mlr3verse`
2. `precommit::use_precommit()`.
3. ???

**Comment by pat-s** [comment]
Downgraded to pre-commit v2.3.0 but still the same issue (mlr here as an example. I don't think the repo matters)

<img width="282" alt="image" src="https://user-images.githubusercontent.com/8430564/84691941-514fa600-af45-11ea-8355-4c5af5798f64.png">

**Comment by lorenzwalthert** [comment]
what are your versions for {usethis} and {desc}?

**Comment by pat-s** [comment]
usethis 1.6.1
desc 1.2.0

**Comment by lorenzwalthert** [comment]
Same here, still no problem.

**Comment by lorenzwalthert** [comment]
Which installation method?

**Comment by pat-s** [comment]
pre-commit v2.5.1 was via `brew`
pre-commit v2.3.0 was via `pip`

Used R versions 4.0.1 and 4.1 during the day

**Comment by lorenzwalthert** [comment]
For future reference: We figured out it had to do with end of line conversion that is governed by your git config. Also see the [GitHub Doc](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) on that.
