### ISSUE TITLE
Add support for `gert::git_commit()`

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#182]
Lately I use {gert} a lot for git stuff. Unfortunately pre-commit hooks are not honored here. Support would be great :)

**Comment by lorenzwalthert** [comment]
How could such support look like? (Sorry I don't get what I can do about it 😄).

**Comment by pat-s** [comment]
I don't know, this was just a thing I my head which I wanted to mention in the first place 😅 

Probably support for general pre-commit accounting needs to be added in {gert}?

Maybe this project could mention that {gert} is not supported right now 😄

**Comment by lorenzwalthert** [comment]
I am not sure we should start to mention all the R git clients that don't support git hooks, because {git2r} also does not -.-

**Comment by pat-s** [comment]
I just see this from an informative point of view (for users), it is not your fault that support for these is missing :)

{git2r} also, mh. Maybe there is a discussion about it already?

Closing, since you are now aware of it 👍

**Comment by lorenzwalthert** [comment]
There is one, just search the issues. 👍
