### ISSUE TITLE
Call autoupdate before install_repo

### ISSUE THREAD

**Issue by krzyslom** [lorenzwalthert/precommit#184]
Hello,
congratulations on bringing the package to CRAN!
I just downloaded the latest version and realized, that at the moment `autoupdate` function is called right after the `install_repo` one. The latter was moved [at the very beginning of the flow](https://github.com/lorenzwalthert/precommit/commit/e3b1e0e00a2a5ef2f64e6625ead6850de72b0f9a#diff-c9a33000e506e95bca8089aa91efd8b2R39). Then it came back, but [right before `autoupdate`](https://github.com/lorenzwalthert/precommit/commit/93d43ce8b1b71366a5b130faaf183ef28d4c5231#diff-c9a33000e506e95bca8089aa91efd8b2L39).
`use_precommit` results in hooks being installed in the default version, before the config file is updated. When issuing the first commit, updated versions of hooks have to be installed, making the previous installation superfluous.
If there is no reason for `autoupdate` to be executed at the very end, then I believe it could switch back places with `install_repo`.

**Comment by lorenzwalthert** [comment]
Thanks @krzyslom. I am not sure why I did that, the commit messages might also be a bit misleading. Let swap things and see if unit tests work. I created #185.
