### ISSUE TITLE
.Rbuildignore is written to working directory

### ISSUE THREAD

**Issue by krzyslom** [lorenzwalthert/precommit#188]
I'm running precommit@b5899e7. When passing R project path to `root` param `.Rbuildignore` file is written in current working directory instead of the project one.

Steps to reproduce:
```{r}
open <- FALSE
pkg <- "pkg"
usethis::create_package(pkg, open = open)
git2r::init(pkg)
precommit::use_precommit(open = open, root = pkg)
```

I believe this line
https://github.com/lorenzwalthert/precommit/blob/0c4bcbe3f7b2ac76f8764412c7e6bd3325625329/R/config.R#L59
should be
```{r}
usethis::write_union(fs::path(root, ".Rbuildignore"), escaped_name_target)
```

I can provide PR if you like.

**Comment by lorenzwalthert** [comment]
Indeed. Thanks. PR welcome yes.
