### ISSUE TITLE
Roxygen cache not invalidated when function signature changes

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/precommit#213]
Since we only check roxygen2 comments, we don't invalidate the cache currently when the function header changes, e.g. from 
```r
#' comment
f <- function(x) {
  ...
}
```
to 
```r
#' comment
f <- function(x, y) {
  ...
}
```

**Comment by lorenzwalthert** [comment]
This might be also a problem with R6. @pat-s have you experienced problems here? Looks like with this PR, any change in a line (after comment removal) with `function(` in it should trigger an invalidation so we are safe.

Also see https://roxygen2.r-lib.org/articles/rd.html#r6

**Comment by pat-s** [comment]
This means a change in a signature would not cause a re-styling? I don't think I've experience this in a way that I would make me suspicious something is going wrong. 

AFAIU one would not recognise a direct failure but just styling silently being skipped because the cache is used, correct?

**Comment by lorenzwalthert** [comment]
No, this refers to the roxygenize hook, not to the styler hook. If you change the function declaration without changing any roxygen comment, the cache of precommit (not styler) is not invalidated with the master branch currently because we only check if the diff contains the regex `^#'`.

**Comment by lorenzwalthert** [comment]
Another one is r-lib/styler@1e9f254. Not sure what's the problem.
