### ISSUE TITLE
Missing standard path location (Apple Silicon M1, homebrew)

### ISSUE THREAD

**Issue by adamblake** [lorenzwalthert/precommit#239]
Homebrew installs pre-commit to `/opt/homebrew/bin/pre-commit` on computers with the Apple Silicon M1 chip.

**Comment by lorenzwalthert** [comment]
Thanks for reporting. Do you want to add it to the locations that are checked: https://github.com/lorenzwalthert/precommit/blob/master/R/exec.R#L126
