### ISSUE TITLE
Potential new hook: `urlchecker::url_update()`

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#242]
https://github.com/r-lib/urlchecker

Currently using it before releasing to CRAN but this might be desirable as a pre-commit hook eventually.

**Comment by pat-s** [comment]
Yeah if the repo is large / has many URLs it takes some seconds. It could profit from caching like {styler} but this would be a different thing.

Maybe it would be sufficient for most people to be integrated by default into `devtools::submit_cran()`.

**Comment by pat-s** [comment]
The let's close here again 🙂

**Comment by lorenzwalthert** [comment]
I am not totally against it xD. People can always opt out but I think there is also a separation of tasks, e.g. running R CMD check on each commit seems too much and sth better offloaded to CI/CD, url checking possibly as well.
