### ISSUE TITLE
New hook: no-debug-statement

### ISSUE THREAD

**Issue by lukasfeick-sw** [lorenzwalthert/precommit#290]
I would like to contribute a hook similar to [no-browser-statement](https://github.com/lorenzwalthert/precommit/blob/master/inst/hooks/exported/no-browser-statement.R) which also checks for leftover `debug()` and `debugonce()` statements in the committed code. This would basically be the R-specific variant of the existing `debug-statements` hook which AFAIK currently only works for Python.

Another option would be to include this in the existing `no-browser-statement` hook but I think I'd generally prefer an additional hook to allow the end user more control.

Happy to open a PR if there's interest.

**Comment by lorenzwalthert** [comment]
Cool. Thanks. I agree we should leave the no-browser hook as is for backwards compatibility. 

Maybe we should make a new hook that includes all the debugging stuff, and use options to specify which types of statements are checked. Like 
```yaml

    -   id: no-debugging
        args: [--browser, —debug, —debugonce]
```

**Comment by lukasfeick-sw** [comment]
Sounds good! As for backwards compatibility, we could then simply have an alias for `no-browser-statement` which points to `no-debugging --browser`. This would probably make maintenance easier in the long run.

**Comment by lorenzwalthert** [comment]
Yes. Sure.  You can go ahead with the implementation. You can find some hints for how to implement functionality, tests etc.  in CONTRIBUTING.md.
