### ISSUE TITLE
Document GitHub Action workflow

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/precommit#291]
pre-commit.ci might not work always due to system dependencies, plus it requires auth for a new GitHub App vendor, which might be a bit suspicious for some people. Hence, it would be better to also give people a GitHub Actions workflow template.

**Comment by lorenzwalthert** [comment]
@scottgigante I saw your GitHub Actions workflow for pre-commit in https://github.com/openproblems-bio/openproblems/blob/main/.github/workflows/pre-commit.yml. Since you appear to maintain it over there, I wondered if you are interested in contributing it (without the Python stuff probably) to {precommit} and maintain it (there might be some changes over time). I'd include you as a package co-author if you want.

**Comment by lorenzwalthert** [comment]
I think we'd have to create a vignette for CI/CD to describe the options and pros and cons. Also, `use_pre_commit()` should also give the user the change to set CI/CD up directly, either via GitHub Actions template or be directed to the GitHub Auth setting to enable the pre-commit app.

**Comment by scottgigante** [comment]
Hi @lorenzwalthert I would love to help out with this, but I don't currently have capacity for any side projects and don't expect to at least for another month or so. If you would rather go ahead without me, I'm more than happy for you to copy that actions template as a starting point.
