### ISSUE TITLE
New hook: pkgdown::build_site()

### ISSUE THREAD

**Issue by b4D8** [lorenzwalthert/precommit#297]
Hi,

Thanks your for developing this great package!

I think it would be convenient to provide yet another git pre-commit hook for [pkgdown](https://github.com/r-lib/pkgdown)::[build_site()](https://pkgdown.r-lib.org/reference/build_site.html) for those not using the github action.

Then, it could be coupled with a git post-commit hook to deploy with rsync for instance, and provide a great workflow for those self-hosting their documentation website.

I just started learning about git hooks recently and could try to give it a shot but I think I will need some help...

Good day!

**Comment by lorenzwalthert** [comment]
Thanks for the suggestion @b4D8. As with https://github.com/lorenzwalthert/precommit/issues/15, I don't want to add long-running hooks. You can still do so as a local hook as described here or check out some local hooks are implemented in this repo.
