### ISSUE TITLE
roxygenise hook fails when dependency uses drat in Additional_repositories

### ISSUE THREAD

**Issue by MarkMc1089** [lorenzwalthert/precommit#310]
I have a dependency in my `DESCRIPTION` that is a package on GitHub. It uses `{drat}` to pull in an additional dependency also on Github. It works when I use `devtools::install_github("MarkMc1089/nhsbsaR")`). But when I use `precommit `with the `roxygenise `hook I get error:

```
stderr:
    During startup - Warning message:
    Setting LC_CTYPE=C.UTF-8 failed
    Error: package 'nhsrtheme' is not available     <----This is a dependency of nhsbsaR and is on GitHub
    Traceback (most recent calls last):
    15: renv::install(commandArgs(trailingOnly = TRUE))
    14: retrieve(names(remotes))
    13: handler(package, renv_retrieve_impl(package))
    12: renv_retrieve_impl(package)
    11: renv_retrieve_github(record)
    10: renv_retrieve_package(record, url, path)
     9: renv_retrieve_successful(record, path)
     8: retrieve(package)
     7: handler(package, renv_retrieve_impl(package))
     6: renv_retrieve_impl(package)
     5: records[[package]] %||% renv_retrieve_missing_record(package)
     4: renv_retrieve_missing_record(package)
     3: renv_available_packages_latest(package)
     2: stopf("package '%s' is not available", package)
     1: stop(sprintf(fmt, ...), call. = call.)
    Execution halted
```

The relevant part of my DESCRIPTION is:
```
Imports: 
    ...,
    nhsbsaR (>= 0.0.0.9000),
    ...
Additional_repositories: 
    https://MarkMc1089.github.io/drat
```
And my precommit config yaml contains:

```
    -   id: roxygenize
        additional_dependencies:
        ...
        -    MarkMc1089/nhsbsaR
        ...
```

Adding the sub-dependencies works:
```
    -   id: roxygenize
        additional_dependencies:
        ...
        -    MarkMc1089/nhsbsaR
        -    MarkMc1089/nhsrtheme
        ...
```

It is OK for small packages, but could become difficult to keep track of if the dependency tree grows! Is there some way to get this to work without adding all the extra dependencies?

**Comment by lorenzwalthert** [comment]
Thanks for the clear description @MarkMc1089. {precommit} does not try on `devtools::install_github("MarkMc1089/nhsbsaR"))`, but uses `renv::install("MarkMc1089/nhsbsaR"))`. Can you confirm that with this command, the problem occurs too? If that’s the case, filing this issue in rstudio/renv would be the next step in my opinion.

**Comment by MarkMc1089** [comment]
Thanks for the quick reply @lorenzwalthert ! `renv` gives the error `Error: package 'nhsrtheme' is not available`.

I'll see if I can change something that allows that to work.

**Comment by MarkMc1089** [comment]
Was simple to fix - just added the dependency to `Remotes `in `DESCRIPTION`.
