### ISSUE TITLE
Commit Fail

### ISSUE THREAD

**Issue by arbues6** [lorenzwalthert/precommit#316]
Hi there, 

I've been trying to Commit changes to a project through RStudio and I didn't manage to make it work anyhow. 
I had similar trouble as https://github.com/lorenzwalthert/precommit/issues/169 , but since the author of that post didn't detail his issue, I wasn't able to reproduce it. 

When I commit, I obtain the following error:

style-files..............................................................Failed
- hook id: style-files
- exit code: 1

Error in packageVersion("precommit") : 
  there is no package called ‘precommit’
Execution halted

spell-check..........................................(no files to check)
Skippedlintr....................................................................Failed
- hook id: lintr
- exit code: 1

Error in loadNamespace(x) : there is no package called ‘docopt’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

readme-rmd-rendered..................................(no files to check)
Skippedparsable-R...............................................................Passed
no-browser-statement.....................................................Passed
Check for added large files..............................................Passed
Fix End of Files.........................................................Passed
Don't commit common R artifacts......................(no files to check)Skipped

The precommit and docopt packages are already installed, and the .libPaths() points to the folder where these packages can be found. Besides, as suggested in https://github.com/lorenzwalthert/precommit/issues/221,  I created an environment variable of "R_LIBS_USER" that points to the folder returned by .libPaths(). 
My guess was that there was a directory problem, but I don't know how to fix it (I tried reinstalling R and RStudio from scratch too). 

I hope someone can help me, please, thanks a lot! :)

**Comment by lorenzwalthert** [comment]
HI @arbues6, sorry to hear you are having such trouble. Are you using the latest version of the package (`remotes::install_github('lorenzwalthert/precommit')`) and the latest hook version (`$ pre-commit autoupdate`)? Also, as described in `NEWS.md`, recent versions of the hooks don't rely on your global R package library, as {precommit} uses {renv} to create a separate environment with the relevant packages. You mention you are running things from RStudio. Did you try to commit from the terminal, e.g. with `$ git commit` also?

**Comment by aarbues** [comment]
Hi @lorenzwalthert , thanks for replying so fast. 

I am using the latest versions (autoupdate returns two messages of "already up to date").
Running things from the terminal returns the same errors as the original message. Let me know if you need more info to reproduce the error. 

Thanks again,

**Comment by lorenzwalthert** [comment]
The other issue is no longer relevant for you I think. Please remove `.git/pre-commit` in your repo and call `$ pre-commit prune` and then in R `precommit::use_precommit()`.

**Comment by aarbues** [comment]
`.git/pre-commit` doesn't seem to be an existing file.

_____________
ls -a
.			.git			style-files
..			.gitignore		testPreCommit.R
.Rhistory		.pre-commit-config.yaml
.Rproj.user		TestPrecommit.Rproj
_____________

Besides, it is not possible to prune through pre-commit (pre-commit: error: argument command: invalid choice: 'prune' (choose from 'autoupdate', 'clean', 'hook-impl', 'gc', 'init-templatedir', 'install', 'install-hooks', 'migrate-config', 'run', 'sample-config', 'try-repo', 'uninstall', 'help')).

**Comment by lorenzwalthert** [comment]
ok my bad, I mean delete the file in `.git/hooks/pre-commit` and run `$ pre-commit clean` and then try again.

**Comment by aarbues** [comment]
That did the trick, it works! 
Thanks again Lorenz

**Comment by lorenzwalthert** [comment]
👍. I guess the only problem is that I still don’t understand how you ended up like this.
