### ISSUE TITLE
Add hook for parseable Rmd

### ISSUE THREAD

**Issue by pwildenhain** [lorenzwalthert/precommit#319]
I use Rmd's a lot for my analysis, it would be nice to ensure that my Rmds are parseable (in addition to my R files)

Happy to contribute, it would be nice if you could point me in the right direction

I saw that there was an interesting R bloggers post here: https://www.r-bloggers.com/2021/09/pre-commit-hook-for-processing-readme-rmd/ but I'm not sure if that works well with the infrastructure you have set up here.

**Comment by lorenzwalthert** [comment]
Hi @pwildenhain, great suggestion. The hook you linked is based on the *bare* git mechanism for pre-commit hooks. We build on top of [pre-commit.com](pre-commit.com), which is an abstraction layer on top of the bare mechanism. We also implemented the equivalent for the readme knitting in https://github.com/lorenzwalthert/precommit/blob/main/inst/hooks/exported/readme-rmd-rendered.R.

So for your concrete request, I think we should extend the [existing hook](https://github.com/lorenzwalthert/precommit/blob/main/inst/hooks/exported/parsable-R.R). We could `knitr::purl()` and write the content to a `tempfile()` and then use `parse()` as we do now. Then, we need to also adapt the [file filter](https://github.com/lorenzwalthert/precommit/blob/main/.pre-commit-hooks.yaml#L36) to make sure R markdown  files are passed to the hook. Are you interested in a PR? You can debug the hook also simply from the terminal like `$ precommit/inst/hooks/exported/parsable-R.R your-rmd.Rmd` or run the lines in the file interactively in your R terminal.

**Comment by pwildenhain** [comment]
Great instructions! I have a PR ready and waiting 🤓

**Comment by lorenzwalthert** [comment]
Great, thanks for your contributions. If you are interested, I forgot to mention `CONTRIBUTING.md`, but just realized it needs updates. If you are interested, I would appreciate a PR since you went through the process now.

**Comment by pwildenhain** [comment]
I actually followed along with what was in CONTRIBUTING.md and it got me pretty far 

I didn't have any success setting up a development environment though/running tests locally so I might not be the best candidate for updating it 😬

I was able to use renv but was having trouble installing devtools, and at that point figured I would just take my chances with the great CI you have set up.

**Comment by lorenzwalthert** [comment]
Well {renv} should only be used for deployment, not development. Maybe that and paths should be updated in the `CONTRIBUTING.md` at least.
