### ISSUE TITLE
styler hook can't find non-standard `styler` package

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#332]
The following 

```r
    -   id: style-files
        args: [--style_pkg=styler.mlr, --style_fun=mlr_style]
```

causes

```
style-files..............................................................Failed
- hook id: style-files
- exit code: 1

Using persistent cache at /Users/pjs/Library/Caches/org.R-project.R/R/R.cache 
[1] "cache root set to " "\"styler-perm\""   
Error in loadNamespace(x) : there is no package called ‘styler.mlr’
Calls: eval ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

I haven't found an easy way to install `styler.mlr` into the cache so that it knows of its existence. What's the best way to do so? I think for users it might be great if this could somehow happen automatically - maybe one can specify the repo slug (e.g. `mlr-org/styler.mlr`) so that it can be installed via `renv` in the background?

**Comment by lorenzwalthert** [comment]
You need `mlr-org/styler.mlr` in `additional_dependencies`. Every hook repo gets its own renv, so the global installation is irrelevant. Maybe the error message could be more helpful.

**Comment by lorenzwalthert** [comment]
Also, the Cache That is mentioned in the output above is for storing hashes of styled code, has nothing to do with whether {styler} or {styler.mlr} is used.

**Comment by pat-s** [comment]
> You need mlr-org/styler.mlr in additional_dependencies. Every hook repo gets its own renv, so the global installation is irrelevant. Maybe the error message could be more helpful.

Ah -  do I need a second `additional_dependencies` block for the style hook? :) Because I included the package within the already existing one under the `roxygenize` hook but this did not work.

**Comment by pat-s** [comment]
The GH PR hook though failed to install the dependency: https://results.pre-commit.ci/run/github/157852588/1638528864.dCMQcDDsQ7SkQBqc34Ks5w

**Comment by lorenzwalthert** [comment]
I think the repo {styler.mlr} must be public for this to work. We can think about supporting private repos later, not sure pre-commit has already a solution for this. 

There is already an issue for that: https://github.com/mlr-org/styler.mlr/issues/17

**Comment by lorenzwalthert** [comment]
> Ah - do I need a second additional_dependencies block for the style hook?

Yes. Every hook repo gets its own renv but when you have additional dependencies per hook, it will create separate environments for every hook even.

**Comment by lorenzwalthert** [comment]
Also cool that you are using pre-commit.ci. You can be my test person and provide feedback 😊. Did the setup work well?

**Comment by pat-s** [comment]
> I think the repo {styler.mlr} must be public for this to work. We can think about supporting private repos later, not sure pre-commit has already a solution for this.

👍 Made it public, was just an oversight that it was not yet.

> Also cool that you are using pre-commit.ci. You can be my test person and provide feedback 😊. Did the setup work well?

Happy to! I just allowed repo access and then the PR check automatically appeared in repos that have a precommit YAML.
