### ISSUE TITLE
`deps_in_desc` hook: option to exclude files

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#352]
I have a [data-helper script](https://github.com/mlr-org/mlr3spatiotempcv/blob/main/data-raw/cookfarm_sample.R) in `data-raw` which uses some packages to prepare the data which should not be listed in the DESCRIPTION file of the package.

It would be great if I could exclude this script from the `deps_in_desc` hook, e.g. via an `exclude` argument, similar to the `forbid-to-commit` hook.

**Comment by lorenzwalthert** [comment]
Every hook has a set of config options like `exclude`. That’s pre-commit, not {precommit}.

**Comment by lorenzwalthert** [comment]
See *other hooks settings* in https://lorenzwalthert.github.io/precommit/articles/available-hooks.html#good-to-know

**Comment by pat-s** [comment]
Awesome, thanks for sharing and sorry for overlooking 🙏
