### ISSUE TITLE
`snippet_generate('additional-deps-roxygenize')` might not cover all required deps

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#353]
I've run `precommit::snippet_generate('additional-deps-roxygenize')` in the main branch of `mlr3viz` and got the following response:

```r
precommit::snippet_generate('additional-deps-roxygenize')
Generating snippet using CRAN versions. If you need another source, specify with syntax that `renv::install()` understands (see examples in help file). 

    -   id: roxygenize
        # roxygen requires loading pkg -> add dependencies from DESCRIPTION
        additional_dependencies:
        -    R
        -    checkmate
        -    data.table
        -    ggplot2
        -    mlr3misc
        -    utils
```

Yet the `precommit-ci` run failed [complaining about many deps missing for the roxygenize hook](https://results.pre-commit.ci/run/github/157852588/1640073200.UDwDEO87SG6IJjMlRi5u3Q).

I haven't looked into `precommit::snippet_generate()` yet but it would be great if it could return all packages used in a package which are needed to execute a full roxygenize call successfully? :)

precommit v0.2.2.9007

**Comment by lorenzwalthert** [comment]
This is indeed a regression, #358 should fix it.

**Comment by pat-s** [comment]
Thanks! I see the relation to #306.

WRT to my initial claim, I think the difference is because the packages in "Suggests" are missing. So if there is a reference in a help page to a suggested package, the hook will fail?

I've tried to replicate this locally by deleting the `precommit` and `styler.perm` caches and running `pre-commit run --all-files`. I expected the `roxygenize` hook to fail but it did not.
I also deleted the pkgs in question from my `renv` cache and rerun everything - it still worked.

Do you know why the linked precommit-ci run failed complaining about pkgs listed in "suggests"?
Not complaining about having to install only pkgs listed in "imports" but just wondering why it works 😃

**Comment by lorenzwalthert** [comment]
> So if there is a reference in a help page to a suggested package, the hook will fail?

i think this causes a warning only. 

Also no output is displayed if a hook passes. So if you roxygenize and there are warnings but no files changed and no error occurs, you won’t see any output.

**Comment by lorenzwalthert** [comment]
Roxygenize requires package loading which gives an error if he’s dependencies are not present and a warning if soft dependencies are not present.

**Comment by pat-s** [comment]
Right, makes sense. One does not care about warnings in this case as long as the `man/` files generated correctly.

So requiring only the pkgs in "imports" to let `roxygenize` succeed is sufficient. Thanks for the heads up!

In my OP the hook failed because one file was written - the warning could be ignored. I was just confused because `precommit-ci` outputted these warning and because there were so many, I overlooked the actual reason for the hook fail and was focused on the warnings only.

```r
Warning: [/code/R/as_precrec.R:3] @description Link to unavailable package: precrec::evalmod. there is no package called ‘precrec’
Warning: [/code/R/as_precrec.R:9] @return Link to unavailable package: precrec::mmdata. there is no package called ‘precrec’
Writing NAMESPACE
Writing NAMESPACE
Writing autoplot.LearnerClassifRpart.Rd
```

But other people who may face the same might then find this issue here (hopefully) :)
