### ISSUE TITLE
`codemeta` hook: recommendation needs update

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#354]
The `codemeta` hook tells users to run 

```
Error: codemeta.json is out of date; please re-run codemetar::write_codemeta().
```

Unfortunately `codemetar` is not anymore on CRAN and its replacement `codemeta` has a [glitch in its current CRAN version](https://github.com/cboettig/codemeta/issues/1) which is why many pkgs might need to install the dev version first.

**Comment by lorenzwalthert** [comment]
So are you suggesting `codemeta::write_codemeta()` in the error message. {codemeta} is on CRAN now.

**Comment by pat-s** [comment]
`codemetar` is also back on CRAN now. So there are two pkgs now, `codemeta` and `codemetar`. Given that the current implementation works again, the code can stay as it is? (No strong opinion :) )

**Comment by lorenzwalthert** [comment]
Ok thanks.
