### ISSUE TITLE
Option to execute certain hooks only locally and not on `precommit-ci`

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#355]
With all the small issues related to `precommit-ci` (timeout, missing deps, etc.) I think it would be awesome to have a notation in the YAML file to denote which hooks should be only executed locally and which locally and on precommit-ci.

E.g. I would like to keep the `roxygenize` hook locally as it is quite helpful and uncritical once a local cache exists.
However, this hook has shown to be troublesome on `precommit-ci` which is why I currently need to remove/comment it completely to make both sides happy.

**Comment by lorenzwalthert** [comment]
> To overcome the above limitations, you can:
Disable the hook completely (by commenting out the respective lines in .pre-commit-config.yaml).
Use GitHub Actions as a CI provider instead with precommit::use_ci("gha").
Skip it on CI as described below
```
ci:
    skip: [roxygenize]
```

https://lorenzwalthert.github.io/precommit/articles/ci.html

**Comment by lorenzwalthert** [comment]
It’s documented also when you `precommit::use_precommit()`. Plus on pre-commit.ci
