### ISSUE TITLE
Hook to add roxygen dependencies to the .pre-commit-config.yaml

### ISSUE THREAD

**Issue by MarkMc1089** [lorenzwalthert/precommit#374]
I've written a hook that will check the `DESCRIPTION` file for all dependencies and then update the `.pre-commit-config.yaml` roxygen hook block. Is this something that you would like added to the package? You can see my fork with the new hook at https://github.com/MarkMc1089/precommit

- add your R (with extension) script in inst/hooks/exported and make it executable. See other scripts in inst/hooks/exported for a starting point for setting up your script. - DONE

- register hook in .pre-commit-hooks.yaml. - DONE

- add two unit tests, test manually with pre-commit try-repo and adapt the [end-to-end test](https://github.com/lorenzwalthert/precommit/blob/main/.github/workflows/end-to-end.yml). - TODO

- add a description of the new hook to vignettes/available-hooks.Rmd. Both description and yaml example code. - TODO

As you can see, I still need to add tests. I'll see if I can work this out, might need a bit of help!

**Comment by lorenzwalthert** [comment]
Thanks @MarkMc1089. I kind of like the idea, although I see the following problems:

* Using {yaml} is the safest option to manipulate `.pre-commit-config.yaml` is not possible because then we'd use all comments.
* Using regex seems like a hack. In particular because there are many other arguments (than `additional_dependencies:`) and orders which might be specified. We might end up with a broken `.pre-commit-config.yaml`, which I want to avoid.

This leaves us with a read-only hook, which we could easily implement. Just read the `additional_dependencies:` and check if all of the hard dependencies from `DESCRIPTION` are in there. What do you think of that?

**Comment by MarkMc1089** [comment]
I did think of maybe using `yaml`. I'm not sure what you mean about using all comments? What about having a `read_only` arg? With the addition of a regex capture group it would be simple to snip out whatever is between the `-  roxygen` hook start and wherever `additional_dependencies` appears in the block.

I'm open to making it read only, but just for me personally I only use the `additional_dependencies` arg in the hook so it would be nice to have the option.

**Comment by lorenzwalthert** [comment]
> I'm not sure what you mean about using all comments? 

Sorry, I meant 'removing', fixed my comment.


Can your regex guarantee to not fiddle with [other configs](https://pre-commit.com/#pre-commit-configyaml---hooks)? Like here:

```yaml
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.2.9009
    hooks: 
    -   id: roxygenize
        args: [--style_pkg=styler, --style_fun=tidyverse_style, --cache-root=styler-perm]
        exclude: > 
          (?x)^(
          tests/testthat/in/.*|
          renv/.*
          )$
```

or this
```yaml
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.2.9009
    hooks: 
    -   id: roxygenize
        exclude: > 
          (?x)^(
          tests/testthat/in/.*|
          renv/.*
          )$
        stages: ["push"]
```

Maybe I am not familiar enough with regex but I don't think this can be captured with your regex, which is 
```
"\\s{4}-\\s*id:\\sroxygenize\\n((\\s{8}.*\\n)*(\\s*-\\s*.*\\n)*)",
```

**Comment by lorenzwalthert** [comment]
I think this hook is mostly a convenience function when you change the dependencies of your package, so I don't think it will be triggered often (only on `DESCRIPTION` and `.pre-commit-config.yaml` change). By providing a helpful error message that the user can c/p into `.pre-commit-config.yaml`, we can get 90% convenience and avoid modifying the file in unexpected ways.

**Comment by MarkMc1089** [comment]
There are 3 cases that have any bearing

- `additional_dependencies` tag with some dependencies declared
- Empty `additional_dependencies` tag
- No `additional_dependencies` tag

With a little modification a single regex can handle both case 1 and 2:

`\s{4}-\s*id:\sroxygenize.*\n((\s{8}.*\n)*.*\n\s*additional_dependencies:\s*\n\K(\s+-\s*.*\n)*)`

I admit it is ugly, but it does work. You can see it in action [here](https://regexr.com/6f1jl). Also can see an explanation of how it works. It will basically take something of the form

```
   a n y t h i n g ...
   ...
   ...
    -   id : roxygen#anything ...
        anything ...
        additional_dependencies#anything ...
        -    dep1                                  # works even if there are no dependencies declared
        -    dep2
   a n y t h i n g ...
```
and match the full lines that have the deps on. If the tag has no dependencies already, it will still return an 'empty' match, so inserting anything will work the same.

For the case of no `additional_dependencies` being present, that is easily fixed by, if there _are_ dependencies, add the tag to the end of the hook block, then just use that regex to find the insertion point.

So altogether it would be doable and would work in 99% of cases. But I agree it is not robust enough (not to mention ugly looking with all the regex!). I have to agree, the safest and best option is just the snippet being printed if the check fails.

I'll modify the code and add tests.

**Comment by MarkMc1089** [comment]
I should be able to use `{yaml}` to get the dependencies only. Unless there is something I'm missing?

**Comment by lorenzwalthert** [comment]
Yes, {yaml} is enough. Also, there is some infrastructure code to extract parts of the config. Just search for `yaml`In the source Code. Then you could potentially re-use that or parts of it at least the url of the repo should not be hard coded, it’s defined as a constant somewhere.

**Comment by lorenzwalthert** [comment]
You can already file a pull request, I think it’s easier if we have the git diff to reason about it. Thanks for contributing. For the tests, you can see how tests are implemented for other hooks and figure it out. Or I’ll do it once we have your code.

**Comment by lorenzwalthert** [comment]
Well actually I am not sure we need a new hook. Can’t we just improve the error message for the roxygenize hook (or is it already good enough)?

**Comment by MarkMc1089** [comment]
Actually yeah, seems a bit overkill to have this as a hook. Better to do as part of the existing roxygenise hook. I cannot remember just how the error shows up. I originally just wanted to automate adding the deps, but after the discussion here I see this will be hard to make foolproof.

After you've had a look at the current way this is handled just let me know if you want it tweaked perhaps?

**Comment by lorenzwalthert** [comment]
I actually played around with it already quite a bit so I think I am happy with the error message. Sorry for the back and forth.
