### ISSUE TITLE
How to set up renv properly?

### ISSUE THREAD

**Issue by MarkMc1089** [lorenzwalthert/precommit#376]
I'm trying to get `{renv}` to work with a fork of the repo, but when I check the package it seems it is not finding a package `{sessioninfo}`:

```
==> devtools::check()

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'sessioninfo'
Calls: loadNamespace ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

Exited with status 1.
```

 Steps I have taken to resolve are updating `{renv}` from 0.14.0 -> 0.15.0-13, running `renv::activate()` and `renv::restore()`.

I also get some warnings when running `renv::diagnostics()`:

```
# Status =============================
WARNING: One or more problems were discovered while enumerating dependencies.

C:/RProjects/precommit/tests/testthat/in/parsable-R-fail.R
----------------------------------------------------------

ERROR 1: C:/RProjects/precommit/tests/testthat/in/parsable-R-fail.R:1:3: unexpected numeric constant
1: 1 1
      ^

C:/RProjects/precommit/tests/testthat/in/parsable-R-fail.Rmd
------------------------------------------------------------

ERROR 1: <text>:7:3: unexpected numeric constant
6: 
7: 1 1
     ^

C:/RProjects/precommit/tests/testthat/in/parsable-R-success.Rmd
---------------------------------------------------------------

ERROR 1: <text>:16:11: unexpected numeric constant
15: 
16:  fas / fk 12
              ^

C:/RProjects/precommit/tests/testthat/in/style-files-fail-parse.R
-----------------------------------------------------------------

ERROR 1: C:/RProjects/precommit/tests/testthat/in/style-files-fail-parse.R:1:4: unexpected ')'
1: 1+ )
       ^
```

These may be expected, they seem to be deliberately unpareable code in tests. The whole output of that diagnostic is very long, but I can add here if that may help resolve this. I have not used renv before so not sure if the results of it are as they should be. But it may just be something simple I am not doing correctly!

**Comment by lorenzwalthert** [comment]
I never use {renv} for checking the package with R CMD check. The hook tests are run within the renv, please see the Vignette in testing and the GitHub actions workflow in `.github/workflows/`.

**Comment by MarkMc1089** [comment]
Thanks for clarifying that. So I would not need to use {renv} locally at all, it is only in GHA workflow it is used?

**Comment by lorenzwalthert** [comment]
Yes, you don't need it. Using {renv} is an integration test, because the end use will run everything in a renv. But that renv does not have {devtools} and {SessionInfo} or other development dependencies (hence the error), because you don't need them at runtime.
