### ISSUE TITLE
Unable to use_precommit in R CMD CHECK

### ISSUE THREAD

**Issue by MarkMc1089** [lorenzwalthert/precommit#391]
I've encountered a bug when running the R CMD CHECK in rstudio. I'm creating a package, initialising git and then attempting to `use_precommit`. Everything works when I run the test outside of R CMD CHECK. But when checking it seems `{precommit}` is unable to confirm pre-commit is installed. The reprex is below. any idea what could be wrong?

Installion of pre-commit framework was done using `install_precommit` from this package. This is on Windows 10. I have also set the R option `precommit.executable` (even tho this should not be necessary as I'm using a standard location for pre-commit).

```
# r_cmd_check_reprex.R
reprex <- function(path) {
  usethis::create_package(path, open = FALSE)
  usethis::local_project(path)

  gert::git_init()
  precommit::use_precommit(open = FALSE, ci = NA)

  invisible(path)
}

```

```
# test_r_cmd_check_reprex.R
test_that("test_reprex", {
  path <- paste0(tempdir(), "/tmppkg")

  expect_equal(reprex(path), path)

  unlink(path, recursive = TRUE)
})

```

Test succeeds outside of R CMD CHECK, but when checking I get:

```
== Failed tests ================================================================
-- Error (test-r_cmd_check_reprex.R:4:3): test_reprex --------------------------
Error in `assert_is_installed()`: pre-commit is not installed on your system (or we can't find it).

If you have it installed and you know where it is, please set the R option `precommit.executable` to this path so it can be used to perform various pre-commit commands from R. If you think this is a standard location, please open an issue on GitHub so we can auto-detect this location in the future and spare new users some set-up troubles.

If you don't know where the executable is stored, go back to the log output that resulted from the installation of pre-commit for hints. If you found it and you think it's a standard location, please open an issue on GitHub so we can auto-detect this location in the future and spare unexpereienced users some trouble.

In case you are totally lost with these messages, you can most likely solve the problems with just using the conda installation method, see https://lorenzwalthert.github.io/precommit/ for how to do this.
Backtrace:
    x
 1. +-testthat::expect_equal(reprex(path), path) at test-r_cmd_check_reprex.R:4:2
 2. | \-testthat::quasi_label(enquo(object), label, arg = "object")
 3. |   \-rlang::eval_bare(expr, quo_get_env(quo))
 4. \-devpacker:::reprex(path)
 5.   \-precommit::use_precommit(open = FALSE, ci = NA)
 6.     \-precommit:::assert_is_installed()
 7.       \-rlang::abort(...)
```

**Comment by lorenzwalthert** [comment]
Thanks @MarkMc1089. Where is your executable located? In your reprex, the R option `precommit.executable` Is unset. Does it also fail if you set the r option to tie respective executable? 
if the executable is in a standard location on Windows 10, I would be open to add this location to the lookup logic.

**Comment by MarkMc1089** [comment]
I think it is in a standard location, since I installed pre-commit using this package:

```
> precommit::path_precommit_exec()
[1] "C:/Users/Mark/AppData/Local/r-miniconda/envs/r-precommit/Scripts/pre-commit.exe"
```

I set the R option globally:

```
> options("precommit.executable")
$precommit.executable
[1] "C:/Users/Mark/AppData/Local/r-miniconda/envs/r-precommit/Scripts/pre-commit.exe"
```

It works fine in most cases. It is only when R CMD CHECK gets to running the tests that it fails. Any ideas to troubleshoot/fix welcome!

**Comment by MarkMc1089** [comment]
Just been troubleshooting this a bit more. The issue is that `getOption("precommit.executable")` is not finding that option during R CMD CHECK. I don't know anything about how R saves the R options, but expect I could manually set this option in the test itself and that should be enough.

**Comment by MarkMc1089** [comment]
Adding the option temporarily did work:

```
test_that("test_reprex", {
  withr::with_options(
    list("precommit.executable" = paste0(
      "C:/Users/Mark/AppData/Local/r-miniconda/",
      "envs/r-precommit/Scripts/pre-commit.exe")), {
    path <- paste0(tempdir(), "/tmppkg")

    expect_equal(reprex(path), path)

    unlink(path, recursive = TRUE)
  })
})
```

I think the issue is not one with `{precommit}` then. If I could figure out how to force R CMD CHECK to honour the globally defined R `options` then this issue would be resolved without relying on hardcoding the option into the test. Do you know how I might be able to do this?

**Comment by MarkMc1089** [comment]
Resolved! Turns out I did not have R_PROFILE_USER env var set. Not sure why setting this resolved the issue, but main thing is it did.
