### ISSUE TITLE
Failure with latest roxygen2

### ISSUE THREAD

**Issue by hadley** [lorenzwalthert/precommit#395]
Not sure why this didn't turn up in my revdepchecks; so please let me know if there's anything I can do to help.

     ══ Failed tests ════════════════════════════════════════════════════════════════
     ── Failure (test-hook-roxygenize.R:95:3): roxygenize works in general ──────────
     `roxygenize_with_cache(list(getwd()), dirs = dirs_R.cache("roxygenize"))` produced no output
     ── Failure (test-hook-roxygenize.R:163:3): warns if there is any other warning ──
     `roxygenize_with_cache(list(getwd()), dirs = dirs_R.cache("roxygenize"))` produced unexpected warnings.
     Expected match: Missing name
     Actual values:
     * [blur.R:4] Block must have a @name
     ℹ Either document an existing object or manually specify with @name
     ── Failure (test-hooks.R:293:1): (code run outside of `test_that()`) ───────────
     paste(contents, collapse = "\n") does not match "Writing flie.Rd".
     Actual value: ""
     Backtrace:
     ▆
     1. └─precommit:::run_test(...) at test-hooks.R:293:0
     2. └─precommit:::run_test_impl(...)
     3. └─precommit:::hook_state_assert(...)
     4. └─purrr::map2(...)
     5. └─precommit .f(.x[[1L]], .y[[1L]], ...)
     6. └─testthat::expect_match(...)
     7. └─testthat:::expect_match_(...)

**Comment by lorenzwalthert** [comment]
yes I also wondered 🙃. It's a check to make sure the roxygen hook works, but I am quite sure what I wanted to test does not depend on that specific behaviour (which changed), so I'll change the test and submit to CRAN. Thanks for checking up on me though, really appreciate it. Have a nice weekend.
