### ISSUE TITLE
lintr failing due to missing packages

### ISSUE THREAD

**Issue by KyleDCox** [lorenzwalthert/precommit#397]
### Version Info
- python: 3.9.4
- pre-commit: 2.19.0
- R: 4.0.0
- renv: 0.15.4
# Description of Issue
Errors are generated by missing package `broomExtra`; however `broomExtra` is installed and available from within the project environment. I've tried reinstalling `broomExtra`, but that did not solve the issue. I've tested with and without using `renv` to control the project environment, and the error is the same in both scenarios.  
For completeness, the relevant content in my DESCRIPTION and NAMESPACE files are the following:  
DESCRIPTION:  
`Imports: dplyr, multcomp, ggplot2, stringr, broomExtra, doBy, stats, lubridate, lme4`  
NAMESPACE:  
```
exportPattern("^[[:alpha:]]+")
import(multcomp)
import(dplyr)
import(ggplot2)
import(stringr)
import(broomExtra)
import(doBy)
import(lme4)
importFrom("stats", "confint", "reorder", "anova", "aov")
importFrom("lubridate", "mdy_hms")
```  
This is my first time using precommit for R package development, and I followed the setup instructions [here](https://lorenzwalthert.github.io/precommit/). Note, my package passes build checks and builds without errors.
# Error Log
![image](https://user-images.githubusercontent.com/29613355/168703366-eb9dbf62-299d-4813-bf92-a653636ac61c.png)

**Comment by lorenzwalthert** [comment]
Hi 👋 

you need to manually specify additional dependencies in `.pre-commit-config.yaml` as {precommit} creates its own renv: 

```yaml

    -   id: lintr
        additional_dependencies:
        -    cli

```

**Comment by lorenzwalthert** [comment]
Maybe we need to patch `loadNamespace()` to give a more helpful error message. This has come up a few times now I feel.

**Comment by lorenzwalthert** [comment]
Do you know by any chance why {lintr} needs that package? To my knowledge, it does not load the package under linting does it?

**Comment by KyleDCox** [comment]
Thanks for your prompt response!  
With your advice and further testing, I was able to solve the error two ways:

1. Adding broomExtra as a dependency (as described above)
2. Instead of adding broomExtra as a lintr dependency, replacing all instances of `broomExtra::foo()` to `foo()` within my code, and changing my namespace's `import(broomExtra)` to `importFrom("broomExtra", "foo")`  

Unfortunately, solving this error revealed another:  
![image](https://user-images.githubusercontent.com/29613355/168848819-c85c7cb0-0192-4d1a-98ba-e27e17be377f.png)  

Interestingly, if I run this without using renv, then only two of the three error messages persist. Also, using lintr on the directory outside precommit gives no errors.  

I'll continue poking around my code and trying additional changes.

**Comment by lorenzwalthert** [comment]
Ok, thanks. Can you make sure {lintr} and {broomExtra} package versions correspond between the two renvs? Accoring to `renv.lock`, {precommit} uses:

* r-lib/lintr@f1643b7430a769947a862c4cd37d0e930bd32f50
* broomExtra from CRAN, as of your install time. 

`additional_dependencies` takes the syntax explained in the [pre-commit docs](https://pre-commit.com/#r):
> When specifying [additional_dependencies](https://pre-commit.com/#config-additional_dependencies) for R, you can use any of the install argument formats understood by [renv::install()](https://rstudio.github.io/renv/reference/install.html#examples).

**Comment by lorenzwalthert** [comment]
All under the assuption that you use the latest version of the hooks (after `precommit::autoupdate()`).

**Comment by KyleDCox** [comment]
Thanks for your help, my package versions are 2.0.1 for {lintr} and 4.3.2 for {broomExtra}. For some reason, {broomExtra} and several other packages were installed from RSPM instead of CRAN. Changing to CRAN didn't make a difference.  

>      [r-lib/lintr@f1643b7](https://github.com/r-lib/lintr/commit/f1643b7430a769947a862c4cd37d0e930bd32f50)  

Thanks for linking the specific {lintr} release. When linting my code with that release I reproduce the error coming from {precommit}'s lintr step:  
```
> lintr::lint_dir("R")
.Error in bdexpr[[1L]] : object of type 'symbol' is not subsettable
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> head(warnings())
Warning messages:
1: In while (as.character(bdexpr[[1L]]) == "{") bdexpr <- bdexpr[[2L]] :
  the condition has length > 1 and only the first element will be used
2: In while (as.character(bdexpr[[1L]]) == "{") bdexpr <- bdexpr[[2L]] :
  the condition has length > 1 and only the first element will be used
3: In while (as.character(bdexpr[[1L]]) == "{") bdexpr <- bdexpr[[2L]] :
  the condition has length > 1 and only the first element will be used
4: In while (as.character(bdexpr[[1L]]) == "{") bdexpr <- bdexpr[[2L]] :
  the condition has length > 1 and only the first element will be used
5: In while (as.character(bdexpr[[1L]]) == "{") bdexpr <- bdexpr[[2L]] :
  the condition has length > 1 and only the first element will be used
6: In while (as.character(bdexpr[[1L]]) == "{") bdexpr <- bdexpr[[2L]] :
  the condition has length > 1 and only the first element will be used
```
It seems like this might be a problem with that {lintr} release and not {precommit}.

# 
> All under the assuption that you use the latest version of the hooks (after `precommit::autoupdate()`).  

Might be a separate issue:  
I hadn't been running `precommit::autoupdate()`, but when I do it sets `rev:` in `.pre-commit-config.yaml` to 0.1.3.9014, which then gives the following error when committing: 
```
[ERROR] The hook `roxygenize` specifies `additional_dependencies` but is using language `script` which does not install an environment.  Perhaps you meant to use a specific language?
```

**Comment by lorenzwalthert** [comment]
Ok, then I'll create a patch release that will use more recent {lintr} to solve the first problem.

For the second problem, please see #399 and the solution propsed in #400.

**Comment by KyleDCox** [comment]
I'm using {precommit} 0.2.2, and `precommit::autoupdate()` still gives the warning message:  
```
Warning message:
It seems like you want to use {renv} and {precommit} in the same repo. This is not well supported for users of RStudio and `precommit > 0.1.3.9014` at the moment (details: https://github.com/lorenzwalthert/precommit/issues/342). Autoupdate aborted and `rev:` in `.pre-commit-config.yaml` set to a version compatible with {renv}.
```  
After uninstalling renv from my project, I was able to run `precommit::autoupdate()` without warnings; however, I'm still getting the {lintr} error from {precommit}:  
```
style-files..............................................................Passed
roxygenize...............................................................Passed
use-tidy-description.....................................................Passed
spell-check..............................................................Passed
lintr....................................................................Failed
- hook id: lintr
- exit code: 1

Error in bdexpr[[1L]] : object of type 'symbol' is not subsettable
Calls: <Anonymous> ... imported_s3_generics -> vapply -> FUN -> is_s3_generic -> <Anonymous>
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
Error in bdexpr[[1L]] : object of type 'symbol' is not subsettable
Calls: <Anonymous> ... imported_s3_generics -> vapply -> FUN -> is_s3_generic -> <Anonymous>
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted


readme-rmd-rendered......................................................Passed
parsable-R...............................................................Passed
no-browser-statement.....................................................Passed
deps-in-desc.............................................................Passed
check for added large files..............................................Passed
fix end of files.........................................................Passed
Don't commit common R artifacts......................(no files to check)Skipped
```

**Comment by lorenzwalthert** [comment]
Yes, you need the dev version of {precommit} to so `autoupdate()` allows you to update beyond `0.1.3.9014` and then it should work. You are using an old hook version now.

**Comment by lorenzwalthert** [comment]
sorry this is so frustrating :-(

**Comment by KyleDCox** [comment]
No worries! Thanks for the clarification and help 😄   
I did the above, but still get the {lintr} error within {precommit}. Which version of {lintr} are you using?  
 [r-lib/lintr@f1643b7](https://github.com/r-lib/lintr/commit/f1643b7430a769947a862c4cd37d0e930bd32f50) gives me the same error when trying `lintr::lint()` on any of my R files. However, the version of {lintr} available on CRAN works fine whenever I `lint::lint()`. Is it possible for {precommit} to use the CRAN release of {lintr}?

**Comment by lorenzwalthert** [comment]
Now, {precommit} uses the dev version of {lintr}. You can always override {precommit}'s version via `additional_dependencies:` and specify `lintr`. Since `additional_dependencies:` will get installed after the *base* dependencies, it would just install that version of {lintr} from CRAN and replace the one I specified in my `renv.lock` in this repo. However, that release is quite old and for some reason I can't remember, I wanted to depend on a newer version.

I encourage you to see if using the dev version of {lintr} outside of pre-commit gives you the same error, which I expect. Then, create a [reprex](https://reprex.tidyverse.org/) and post it as an issue on r-lib/lintr so they can fix it, as it seems a {lintr} issue. They are planning to do a release soon so it would be great if that bug fix could be part of it.

**Comment by KyleDCox** [comment]
Ok, so this appears to be some bizarre bug with {lintr} _mostly likely caused by my project environment and package installs_.  
For context, this within an enterprise with the following `sessionInfo`:
```
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux
```

Here are some details:
- I was unable to reproduce this bug using the same R version on a different machine
- Another user of the linux server was able to successfully lint my code with the github version of {lintr} from outside of my project
- I was successfully able to lint that user's code (different project) from within my project
- I was never able to lint my own code from within my project, with and without {renv}  

Since this is unique to my environment/project, it's not worth creating an issue within r-lib/lintr. I should be able to sort this out on my own.

I think you can close this issue. I will try a fresh re-install for all of my R packages.  
Thanks again for all your help and advice :smile:  
Apologies that this is most likely just a ghost in my machine :ghost:
-Kyle

**Comment by lorenzwalthert** [comment]
Ok, thanks for the explanation and good luck.
