### ISSUE TITLE
Can additional dependencies include private github repositories?

### ISSUE THREAD

**Issue by danielinteractive** [lorenzwalthert/precommit#406]
Hello developers,

is pre-commit able to fetch private github repos as dependencies?
I am currently trying to setup the precommit config yaml for an R-package that depends on another private github repository R-package, but it seems it cannot find it - my guess is because it is internal and therefore (?) not exposed in the API?
In particular, https://api.github.com/repos/orgname/reponame cannot be retrieved and gives 404.
Are any workarounds possible here? Maybe it is something we can fix in our github settings? or provide tokens or so?

Thanks,
cheers
Daniel

**Comment by lorenzwalthert** [comment]
The install process is implemented in the upstream framework https://pre-commit.com, as part of the `language: r` functionality (I contributed it). The source code is [here](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/languages/r.py#L145). Did you figure out how to install the private dependency with {renv} outside a pre-commit setting? Then, we can maybe file an issue upstream to support it. There were a few issues upstream on configuration of hook environments on install, in particular https://github.com/pre-commit/pre-commit/issues/758, but it seems to me that we'll probably need another solution than those proposed in the issue, as `additional_dependencies` won't work for us.

**Comment by danielinteractive** [comment]
Thanks @lorenzwalthert - I will check in our team if we can use {renv} for this, and then come back

**Comment by lorenzwalthert** [comment]
Well not exactly. Clarification: your repo does not have to use renv. pre-commit has its own install mechanisms based on renv. So all I need you to do is to figure out how to install from a private repo with renv in *any* context. Then we will figure out how to adapt the upstream framework.

**Comment by danielinteractive** [comment]
Yeah that is what I meant :-) thx!

**Comment by lorenzwalthert** [comment]
Any update here? Otherwise I'd vote to close this.

**Comment by danielinteractive** [comment]
Hm I think I solved this in the end but forgot how. So we can close
