### ISSUE TITLE
forbid_to_commit regexp patterns are formulated incorrectly

### ISSUE THREAD

**Issue by mpadge** [lorenzwalthert/precommit#409]
**Before filing a bug**

- [x] I have installed the latest dev version of {precommit} with `remotes::install_github('lorenzwalthert/precommit')`
- [x] I have installed the latest hook revisions (update with `precommit::autoupdate()`)
- [x] I have installed the latest release of the upstream Python framework pre-comit as described under the [update instructions](https://lorenzwalthert.github.io/precommit/dev/articles/precommit.html#update).

**Describe the bug**

The `forbid_to_commit` patterns are like this:
https://github.com/lorenzwalthert/precommit/blob/fcecc1049dbbcdbf2a6662ba295760323f804536/inst/pre-commit-config-pkg.yaml#L69
but they should be like this:
``` yaml
   files: '\.Rhistory$|\.RData$|\.Rds$|\.rds$'
```
But i'm not sure about the details of precommit's regexpr interpreter, so maybe something like:
``` yaml
   files: '\.(Rhistory|RData|Rds|rds)$'
```
:question: 

Either way, in current form, files with these components as intermediate parts of their paths are created routinely by `httptest2`, for example as `<filename>.Rds.R` for a http request that does something with `<filename>.Rds`. Default precommit prevents those files from being committed.

**Expected behavior**

Files with these patterns as *non-terminal* parts of their names should pass `forbid_to_commit`.

Thanks Lorenz, keep up the awesome work!

**Comment by lorenzwalthert** [comment]
Thanks @mpadge. I did not reproduce, but if that's what you experience, I trust you that the pattern is wrong 😄. Seem like 
```
   files: '\.(Rhistory|RData|Rds|rds)$'
```
Should work. Have you tried that yourself in {httptest2}? As you can directly adapt your `.pre-commit-config.yaml`, this shoudl be easy to verify. If so, I am happy to accept a PR to change the templates in `inst/`, or I can also do it myself if you don't have time...

**Comment by mpadge** [comment]
Yep, just tried the regex as you have it above, and it all worked. So they all just need to be changed to that. I'll PR in a moment. Thanks!

**Comment by lorenzwalthert** [comment]
Ok cool. Can you change all files affected? https://github.com/lorenzwalthert/precommit/search?q=files%3A+%27%5C.Rhistory%7C%5C.RData%7C%5C
