### ISSUE TITLE
File editing suggestions presumably points to a wrong filename

### ISSUE THREAD

**Issue by fabianegli** [lorenzwalthert/precommit#444]
precommit::use_precommit() has a bullet point message `Edit .precommit-hooks.yaml to (de)activate the hooks you want to use.` and if I am not mistaken the file should be `.pre-commit-config.yaml` instead.

**Comment by lorenzwalthert** [comment]
That’s right. Thanks for pointing to it. Want to fix it in a PR?

**Comment by fabianegli** [comment]
Sorry for not replying and thank you for the fix.
