### ISSUE TITLE
The defaults are seemingly different in different format checkers

### ISSUE THREAD

**Issue by fabianegli** [lorenzwalthert/precommit#445]
When all hooks are run in an R project it now happens that `styler` will leave long lines that it could split and `lintr` then complains they are too long with more than 80 characters.

1. Can `styler` be configured to break the lines?
2. Can `lintr` be configured to allow longer lines ~100 characters. 80 characters are a bit too short - screens got bigger and generally have a better resolution now than when the 80 characters limit became an industry standard. And good variable names also sometimes add to the line length.

Maybe I am mistaken, but I don't expect any `lintr` errors after `styler` runs successfully.

**Comment by lorenzwalthert** [comment]
> Can styler be configured to break the lines?

Not yet, and it's the most upvoted feature request. #247


> Can lintr be configured to allow longer lines ~100 characters

Possibly, I am not a {lintr} expert. `.lintr` config file is respected.

> Maybe I am mistaken, but I don't expect any lintr errors after styler runs successfully.

True. Please open issues in {lintr} or {styler} if you have concrete problems. We are working towards compatibility. 

All of the above are not {precommit} specific problems though. I just happen to work on {styler} and with contributors of {lintr} so I answered from that perspective. So these are the repos to go to if you experience problems that are unrelated to pre-commit.

**Comment by lorenzwalthert** [comment]
As per *the efaults are seeminlgyy different in different format checkers*, {precommit} does not set any defaults, we just fall back to the defaults of {styler} and {lintr} in that case.

**Comment by lorenzwalthert** [comment]
Ok. Thanks. {styler} won't rename your variables etc. These are linting issues that can't be auto-fixed.
