### ISSUE TITLE
Update to lintr needed?

### ISSUE THREAD

**Issue by joelnitta** [lorenzwalthert/precommit#451]
**Before filing a bug**

- [x] I have installed the latest dev version of {precommit} with `remotes::install_github('lorenzwalthert/precommit')`
- [x] I have installed the latest hook revisions (update with `precommit::autoupdate()`)
- [x] I have installed the latest release of the upstream Python framework pre-comit as described under the [update instructions](https://lorenzwalthert.github.io/precommit/dev/articles/precommit.html#update).

**Describe the bug**

Internal (non-exported) functions that are defined in a separate file from an exported function (e.g., functions in a `utils.R` file) trigger the lintr "`[object_usage_linter] no visible global function definition`" warning. I do not encounter this behavior when running lintr myself with lintr v3.0.2. It seems {precommit} is running v3.0.1 so I suspect that may be causing the problem:

https://github.com/lorenzwalthert/precommit/blob/428e0f9f1051b92f5a2eb7ce306544e1b4face6a/renv.lock#L274

**To Reproduce**
1. Create `utils.R` with a non-exported function
2. Call that function from another file (e.g., `exported.R`)
3. Try to commit `exported.R`

**Expected behavior**
No warning from the lintr

**Additional context**

- My operating system is: Mac OSX
- My project does not use renv

**Comment by joelnitta** [comment]
@lorenzwalthert it certainly looks like you are right - I think I've encountered the same thing as #440. There's one thing I don't understand though: It looks like {precommit} calls [lintr::lint(path)](https://github.com/lorenzwalthert/precommit/blob/467d3cf82d550edff39c52ec45dba39a2dd2bd54/inst/hooks/exported/lintr.R#L27), but when I run `lintr::lint("path_to_R_script")` I don't get any `[object_usage_linter]` warnings like I do from {precommit}.

**Comment by lorenzwalthert** [comment]
Ok. Make sure to not  `devtools::load_all()` before  the {lintr} call. But have you tried also outside RStudio like 
```bash
Rscript -e "lintr::lint(path)" 
```
With the same result? I think maybe {lintr} runs `devtools::load_all()` in RStudio or something like this.

**Comment by joelnitta** [comment]
Ah, that does make the difference. I'm not using RStudio (I use vs-code), but if I run `lintr::lint("path")` in a fresh R session I get the `object_usage_linter` warnings; if I run `devtools::load_all()` first, no warnings. So yes this is the same thing. Closing now since it's a duplicate of #440.
