### ISSUE TITLE
consider using other cran mirror

### ISSUE THREAD

**Issue by clarkliming** [lorenzwalthert/precommit#454]
Hi @lorenzwalthert thank you for this amazing project, it is very helpful.

However, when using this package, I often run into issues with CRAN connectivity issues, usually

could not retrieve available packages for url 'https://packagemanager.rstudio.com/all/latest/src/contrib'

I think it is related to the renv.lock file that this repository is using(please correct me if this is wrong; I tried adding .Rprofile to specify the CRAN but it seems not working as I can see that the command executed will add "options(cran = xx)" in the argument) This CRAN is not very stable in China, and I wonder if you can allow users to specify this, or change to https://cloud.r-project.org/  (Automatic redirection to servers worldwide, currently sponsored by Rstudio).

Thank you in advance.

**Comment by lorenzwalthert** [comment]
The reason we use RSPM is because it allows binary installs on Linux. This is in particular important when building tue image for pre-commit.CI, as there is a timeout. 

When exactly do you fade tue connectivity issue? It should only be for installing the initial environment or updating the hook revision. Which operating system? Please fill out the issue template next time. 🙃

**Comment by clarkliming** [comment]
I am just wondering if we can remove that CRAN setting so that users can leverage on their own `.Rprofile` to restore the renv environment? anyway this is one time set up and users can still use RSPM to install the hooks

**Comment by lorenzwalthert** [comment]
To me, it sounds like the lot problem is the connectivity to RSPM. Can this maybe be fixed on Posit‘s (RStudio‘s) side?

**Comment by lorenzwalthert** [comment]
Also note that if you are on Linux, I don’t think any other out of the box mirror has binaries for Linux except RSPM…

**Comment by clarkliming** [comment]
thank you for the suggestion. I will raise this to Rstudio. 👍
