### ISSUE TITLE
Child Rmd documents pose problems for parsable-R hook?

### ISSUE THREAD

**Issue by IndrajeetPatil** [lorenzwalthert/precommit#457]
In [this](https://github.com/IndrajeetPatil/statsExpressions/pull/205/files) PR, I am adding the `parsable-R` precommit hook to my existing precommit workflow. 

But, as can be seen in [this log](https://github.com/IndrajeetPatil/statsExpressions/actions/runs/3694589521/jobs/6255956240), it fails because it can't seem to access the child document.

```r
Quitting from lines 41-42 (/tmp/Rtmpx5mt01/man/rmd-fragments/statsExpressions-package.Rmd) 
Error in file(con, "r") : cannot open the connection
```

Is this expected?

P.S. Child documents are a good way to keep the documentation DRY (I talk at length about this [here](https://indrajeetpatil.github.io/dry-r-package-development/#/documentation)), and are used by many packages (e.g. [`{pkgdown}`](https://github.com/r-lib/pkgdown/tree/main/man/rmd-fragments)).

**Comment by lorenzwalthert** [comment]
Thanks for reporting. I don't think this is expected. And I am not familiar with child documents. I just know that for non-plain R documents, contents are purled first. Can you run [the hook scripthttps://github.com/lorenzwalthert/precommit/blob/main/inst/hooks/exported/parsable-R.R( locally on the offending file and reproduce the rror

**Comment by IndrajeetPatil** [comment]
True, the file it is having trouble with is [README](https://github.com/IndrajeetPatil/statsExpressions/blob/369f6d71ec080e950ef1729f341301b9dcbb48ec/README.Rmd#L40-L42).

Experimenting with this locally, I figured out the source of the issue: this hook seems to struggle with inbody syntax.

That is, the following produces an error:

````
```{r}
#| child = "man/rmd-fragments/statsExpressions-package.Rmd"
```
````

but this doesn't

````
```{r, child = "man/rmd-fragments/statsExpressions-package.Rmd"}
```
````

I have a hunch that this is going to ultimately trace to https://github.com/rstudio/rmarkdown/issues/2393, so I am closing this here, and just removing the inbody syntax.
