### ISSUE TITLE
Error during environment installation.

### ISSUE THREAD

**Issue by AliSajid** [lorenzwalthert/precommit#469]
**Before filing a bug**

- [X] I have installed the latest dev version of {precommit} with `remotes::install_github('lorenzwalthert/precommit')`
- [X] I have installed the latest hook revisions (update with `precommit::autoupdate()`)
- [X] I have installed the latest release of the upstream Python framework pre-comit as described under the [update instructions](https://lorenzwalthert.github.io/precommit/dev/articles/precommit.html#update).

**Describe the bug**
The entire process stops at the environment installation phase for the [lorenzwalthert/precommit]() hooks repo. I have tried going back and forth in revisions to no avail.

Here's the output from my run: [https://gist.github.com/AliSajid/f2cd3c38a0fe0d9c4d9895678cc0ed9d](https://gist.github.com/AliSajid/f2cd3c38a0fe0d9c4d9895678cc0ed9d)

**To Reproduce**
1. Install `precommit` package
2. Run `precommit::use_precommit()` to install the hooks
3. Run `pre-commit run --all-files`
4. [See error](https://gist.github.com/AliSajid/f2cd3c38a0fe0d9c4d9895678cc0ed9d)

**Expected behavior**
The environment installation should work.

**Additional context**

- My operating system is: MacOS Ventura 13.2
- [X] My project uses {renv}.

**Comment by lorenzwalthert** [comment]
Tanks for the report. What's your R version?

**Comment by AliSajid** [comment]
Hi. Thank you. I'm using R 4.2.2.

**Comment by AliSajid** [comment]
Hi. Pinging as I am still running into this and I am close to submitting the packages to BioConductor

**Comment by lorenzwalthert** [comment]
Is this a public repo so I can try to reproduce the problem myself?

**Comment by AliSajid** [comment]
Oh absolutely. CogDisResLab/drugfindR

**Comment by lorenzwalthert** [comment]
I can't reproduce your problem on my macOS M1 4.2.1. I get the output of running hooks (some are failing due to style and other issues) inside the RStudio terminal or on a macOS Terminal app. I recommend `$ pre-commit clean` and then run `pre-commit install` again, both outside the RStudio terminal.

**Comment by lorenzwalthert** [comment]
Another alternative is to delete all renv caches, but I don't know how that works.

**Comment by AliSajid** [comment]
So this is unusual. I tried both your suggestions but ran into the same issue. It appears that one of the issues I see is that three packages that hit a 404 now have extensions `.tar.gz` and not `.tgz`.

```
    Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tgz' [error code 22]
    Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.methodsS3_1.8.2.tgz' [error code 22]
    Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.oo_1.25.0.tgz' [error code 22]
    Error: failed to retrieve package 'R.cache@0.16.0'
    In addition: Warning messages:
    1: curl: (22) The requested URL returned error: 404
    2: curl: (22) The requested URL returned error: 404
    3: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tgz' [error code 22]
    4: curl: (22) The requested URL returned error: 404
    5: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.methodsS3_1.8.2.tgz' [error code 22]
    6: curl: (22) The requested URL returned error: 404
    Traceback (most recent calls last):
    8: renv::restore()
    7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
    6: retrieve(packages)
    5: handler(package, renv_retrieve_impl(package))
    4: renv_retrieve_impl(package)
    3: renv_retrieve_repos(record)
    2: stopf("failed to retrieve package '%s'", renv_record_format_remote(record))
    1: stop(sprintf(fmt, ...), call. = call.)
    Execution halted
```

**Comment by lorenzwalthert** [comment]
Yeah I also noted that. I am not familiar enough with CRAN to know what that means. But I don't know if it's unusual.  Also, these packages are not archived, i.e. our requirement is the latest version on CRAN. Another thing you can try is to purge and re-install the packages:
```
purrr::walk(("R.cache@0.16.0", "R.methodsS3@1.8.2", "R.oo@1.25.0"), function(pkg) {
  renv::purge(pkg)
  renv::install(pkg)
})
```
This can be done in any renv or outside an active {renv} project.

**Comment by AliSajid** [comment]
So I used the trick of individually purging and reinstalling the renv packages and ran into more such errors. I repeated the process and now have it running without issue. Thank you.

I'm unsure what the issue was but it is solved now. It may be linked to the "Additional packages" list for the roxygen hook. I'll keep you updated. I think we can resolve this here.

Thank you for the excellent package and your prompt and helpful responses.

**Comment by lorenzwalthert** [comment]
Seems like the general solution to delete all caches is to described in [this](https://stackoverflow.com/questions/61297712/how-to-completely-remove-renv-from-an-r-statistics-program) StackOverflow answer: 
```r 
root <- renv::paths$root()
unlink(root, recursive = TRUE)
```
