### ISSUE TITLE
Error: object 'never' not found on git commit

### ISSUE THREAD

**Issue by sempwn** [lorenzwalthert/precommit#473]
**Before filing a bug**

- [X] I have installed the latest dev version of {precommit} with `remotes::install_github('lorenzwalthert/precommit')`
- [X] I have installed the latest hook revisions (update with `precommit::autoupdate()`)
- [X] I have installed the latest release of the upstream Python framework pre-comit as described under the [update instructions](https://lorenzwalthert.github.io/precommit/dev/articles/precommit.html#update).

**Describe the bug**
I encounter the following error when running a `git commit` 

```
[INFO] Installing environment for https://github.com/lorenzwalthert/precommit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from C:\Users\USER\.cache\pre-commit\patch1678401203-36472.
An unexpected error has occurred: CalledProcessError: command: ('C:/PROGRA~1/R/R-41~1.0\\bin\\Rscript.exe', '--vanilla', '-e', '    options(install.packages.compile.from.source = "never", pkgType = "binary")\n            prefix_dir <- \'C:\\\\Users\\\\USER\\\\.cache\\\\pre-commit\\\\repovawmpj_r\'\n        options(\n            repos = c(CRAN = "https://cran.rstudio.com"),\n            renv.consent = TRUE\n        )\n        source("renv/activate.R")\n        renv::restore()\n        activate_statement <- paste0(\n          \'suppressWarnings({\',\n          \'old <- setwd("\', getwd(), \'"); \',\n          \'source("renv/activate.R"); \',\n          \'setwd(old); \',\n          \'renv::load("\', getwd(), \'");})\'\n        )\n        writeLines(activate_statement, \'activate.R\')\n        is_package <- tryCatch(\n          {\n              path_desc <- file.path(prefix_dir, \'DESCRIPTION\')\n              suppressWarnings(desc <- read.dcf(path_desc))\n              "Package" %in% colnames(desc)\n          },\n          error = function(...) FALSE\n        )\n        if (is_package) {\n            renv::install(prefix_dir)\n        }\n        \n    ')
return code: 1
stdout: (none)
stderr:
    During startup - Warning messages:
    1: Setting LC_COLLATE=en_US.UTF-8 failed 
    2: Setting LC_CTYPE=en_US.UTF-8 failed 
    3: Setting LC_MONETARY=en_US.UTF-8 failed 
    4: Setting LC_TIME=en_US.UTF-8 failed 
    Error in options(install.packages.compile.from.source = never, pkgType = binary) : 
      object 'never' not found
    Execution halted
Check the log at C:\Users\USER\.cache\pre-commit\pre-commit.log
```

**To Reproduce**
I have installed Python in Windows 10 using `reticulate` to install miniconda as described in the README. I started with a minimal `.pre-commit-config.yaml` file that reproduces the above error:

```yaml
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9007
    hooks:
    -   id: style-files
```

**Additional context**

- My operating system is: windows 10
- [X] My project uses {renv}.
- [X] the output of `packageVersion('renv')` "0.14.0"

**Comment by lorenzwalthert** [comment]
This is basically what @EzicJ already found in https://github.com/lorenzwalthert/precommit/issues/441#issuecomment-1366550711. My reply then:

Ok I don't get that. Because clearly, in the source code, the word _never_ is [in quotes](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/languages/r.py#L144). Maybe still some problem with the slashes in the executable (`'C:/PROGRA~1/R/R-41~1.0\\bin\\Rscript.exe'`)? Like can you try 
```
C:/PROGRA~1/R/R-41~1.0\\bin\\Rscript.exe -e "print('this')"
# vs 
C:/PROGRA~1/R/R-41~1.0/bin/Rscript.exe -e "print('this')"
# vs 
C:\\PROGRA~1\\R\\R-41~1.0\\bin\\Rscript.exe -e "print('this')"
```
Just to see if it's worth re-raising that in the upstream repo?

If we don't find a solution here, we need to go upstream, basically it's anyways a python pre-commit issue, not an R {precommit} issue.

**Comment by sempwn** [comment]
Thanks for the help and suggestion. All of the above examples you describe provided the expected output

```
[1] "this"
```

Thanks for pointing to the previous comments. I suspect it may be a PATH issue, but following comments in #441 have so far not resolved the error, I'll open an issue in the upstream repo.

**Comment by lorenzwalthert** [comment]
Ok. Great. Please link it back to here.

**Comment by lorenzwalthert** [comment]
@asottile after #441 it's the second windows issue where there is a problem with the R executable and  I think that's a pre-commit issue. Any ideas?

**Comment by asottile** [comment]
this looks like the cygwin weirdness with msys2 executables -- I haven't found a solution to it though :/ -- maybe we need to write out the little scripts into temporary directories and execute them instead of as `Rscript -e` ?

**Comment by lorenzwalthert** [comment]
ok, I am now more lost than before 😢. You mean for the installation of the hook, around the complicated string [`r_code_inst_environment `](https://github.com/pre-commit/pre-commit/blob/6896025288691aafd015a4681c59dc105e61b614/pre_commit/languages/r.py#L101)? Note that `r_code_inst_environment` itself contains code that writes the string to a file (`activate.R`) and is partly dynamic. E.g. `getwd()` is an R command to get the current working directory.

**Comment by asottile** [comment]
yeah right now it's running `Rscript -e bunch/of/code` but if we switched it to `Rscript /some/tmp/file/containing/code` then we wouldn't have to deal with the weirdnesses with windows and msys unquoting

**Comment by lorenzwalthert** [comment]
@sempwn the issue should be fixed with the [latest pre-commit release](https://github.com/pre-commit/pre-commit/releases/tag/v3.3.2). Can you install that release, `pre-commit clean` and `pre-commit install` again and see if it works now?

**Comment by lorenzwalthert** [comment]
Assume this is resolved, re-open otherwise.
