### ISSUE TITLE
Some docs notes

### ISSUE THREAD

**Issue by maelle** [lorenzwalthert/precommit#50]
I'm actually very new to the package, I'll keep track of my thoughts when installing and trying it, maybe it can help. So that's not a [full rOpenSci review](https://github.com/lorenzwalthert/precommit/issues/49#issuecomment-559175450), that's a full newbie review. :baby_chick: (mostly for the README)

* How does it work? What's the magic?

> No magic 😊. Git [provides a mechanism for pre-commit hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks). Since it's cumbersome to copy bash scripts and keep them updated in some hidden `.git/` directory, people wrote frameworks to basically maintain these files. One of them is pre-commit.com. So you call git to commit, git calls its internal hooks, these hooks (bash scripts in the simplest case) are provided by the pre-commit framework. And where does pre-commit get all it's nice hooks from? From us 😊. 

* Make it clearer it's wrapping a framework for git commit hooks?

> This package contains: hooks and wrappers. Hooks are stored in `inst/bin/`. Every hook has an id and the executable (i.e. the path to it) is referenced via the `.pre-commit-hooks.yaml` in this repo. A user only has a `.pre-commit-config.yaml` file in his repo where he lists the ids of the hooks he want's pre-commit to run before every commit. Pre-commit clones this repo and will execute the scripts before every commit. It passes the file names to the executable script (always as last unnamed argument) and potentially other arguments. The repo also contains wrappers. They make extensive use of `system2()` to call the `pre-commit` executable provided by pre-commit.com. Examples are `autoupdate()`, `use_precommit()` and `install_precommit()`, `open_config()` and friends.

* Make it clearer it's an R package, not a collection of hooks?
 > It's both 😊.  The exported functions of the package are the wrappers, facilitators to use pre-commit from the R command line. We could also have put the hook definitions into another repo. Then, this second repo would contain `.pre-commit-hooks.yaml` and `inst/bin/` only. But I felt why not one repo? Also, the repo meets all requirements for an R package and has tests for the hooks.

* Add links for git (happygitwithr?), an intro to hooks somewhere?

> Good idea to link happygitwithr. But I feel like hooks are not that complicated. As the readme states, they are just like tests that are executed before the commit.

* Make system dependencies clearer and add links to how to install Conda on various platforms? e.g. I'm installing miniconda on Ubuntu. Say a further system dependency will be installed by the package, so it's clear what will be installed in the end (Conda, a framework, the package)

> Right. So I think a link to how to install conda should be sufficient for the installation part of conda. What happens when? 1) user must install conda, 2) install the R package (does not install the hooks, although they will be in inst/bin/, but the pre-commit does not know about that. The package is installed to use the wrappers), 3) run `precommit::install_precommit()` installs the pre-commit executable into the conda environment, 3) `precommit::use_precommit()` installs pre-commit into a specific repo (i.e. it puts the hooks scripts into `.git/` via `git clone`.

* Make it clearer what's on the internet? How are hooks accessed? What happens if there's no internet connection?

> No internet connection required, except during installation (`precommit::install_precommit()`and `precommit::use_precommit()`). As stated above, hooks will be placed into `.git/` during calling the  `precommit::use_precommit()` and afterwards you can `precommit::autoupdate()` to basically do a `git pull` (that's what I think happens).

* What will happen when your collaborators don't have any of the things installed? Can they still commit?

> [Two solutions](https://pre-commit.com/#temporarily-disabling-hooks).

* Can you use it outside RStudio?

Yes, all but the `open_config()` and `open_wordlist()` to open files in RStudio. The hooks are working even if you don't have the package installed but the pre-commit was installed via another way like `brew` or `pip install` (as pre-commit will handle these). The package can be used to avoid switching to the bash terminal to run `pre-commit autoupdate` and similar.

* How does one create a new pre-commit hook? Would it help if you stored the pre-commit not in the same repo as your package, so one could see the minimal structure? E.g. I think r-lib/ghactions is different from r-lib/actions?

> How to contribute new hooks is explained in `CONTRIBUTING.md`. It would help to see the minimal structure if the R package and the hook repo was not the same yes. The minimal structure for the hook repo is `.pre-commit-hooks.yaml` and executable files like the one in `inst/bin`. No idea about (gh)actions.

* If I want to contribute a new hook to ensure codemeta.json (docs.ropensci.org/codemetar) is always up-to-date, how do I do that? 

> A hook fails if 1) any input file is modified by the hook or 2) if running the hook script fails. So it's pretty simple for your case. Just create a bash script with shebang, make it executable and run `write_codemeta(".")`, link it in `.pre-commit-hooks.yaml` (with a file filter on `DESCRIPTION`). Just see the `use-tidy-description` hook here: https://github.com/lorenzwalthert/precommit/blob/master/inst/bin/use-tidy-description. In addition, please follow `CONTRIBUTING.md`

(to be continued)

**Comment by maelle** [comment]
```r
Ran `pre-commit autoupdate` to get the latest version of the hooks.
```

this has to happen via the command line?

**Comment by maelle** [comment]
How could I add a local hook if I wanted to do that?

**Comment by lorenzwalthert** [comment]
Thanks a lot @maelle! You mentioned a lot of stuff we could extend the doc on, and it's helpful to have the newbies perspective on the package. I'll try to address these questions later and then we can think about how to update the docs. Thanks a lot.

**Comment by maelle** [comment]
Cool! E.g. the question about whether collaborators can still commit when not having installed all the things is something I'd want to know before using precommit in any project (or even before installing it).

**Comment by lorenzwalthert** [comment]
It was at some point in the doc, probably lost in re-factoring. So for your use case, there are [two solutions](https://pre-commit.com/#temporarily-disabling-hooks). This aspect, we should probably include in the doc of this repo high-up.

A general principle we should highlight in the docs is that we don't aim for comprehensive docs for pre-commit features, as we are only providing a wrapper and pre-commit is well documented.

**Comment by lorenzwalthert** [comment]
Another thing is that pre-commit hooks in general are not supported by `git2r` (currently) so I think this also deserves mention somewhere.

**Comment by maelle** [comment]
what about r-lib/gert btw?

**Comment by lorenzwalthert** [comment]
I don't know. Don't use it.

**Comment by maelle** [comment]
One last remark, I find this package super exciting! which my comments maybe hide.

**Comment by lorenzwalthert** [comment]
> Ran `pre-commit autoupdate` to get the latest version of the hooks. this has to happen via the command line?

This is literally just running `pre-commit autoupdate` in terminal for you.
```r
function () 
{
    system2(path_pre_commit_exec(), "autoupdate")
    usethis::ui_done(paste0("Ran `pre-commit autoupdate` to get the latest version of the hooks."))
}
```

**Comment by maelle** [comment]
Aaaah I read it "run" not "ran", stupid me.

**Comment by lorenzwalthert** [comment]
I tried to answer your questions in the first comment.

**Comment by lorenzwalthert** [comment]
Actually the note about how to to disable hooks is in the usage section of the README.

**Comment by maelle** [comment]
Yes but I still think having the explicit question "What if my collaborators" "You can disable hooks" (with the same link) would be useful to convince a potential user ;-)

**Comment by lorenzwalthert** [comment]
I turned a few of the questions into an FAQ vignette here: https://lorenzwalthert.github.io/precommit/articles/FAQ.html. I also adapted the help files for `use_precommit()`  and `uninstall_precommit()`.

**Comment by maelle** [comment]
Thanks a lot, I think you can close this :-) Is the FAQ vignette linked from the README?

**Comment by lorenzwalthert** [comment]
Thanks. No, but the online documentation in general is linked.
