### ISSUE TITLE
check codemeta is up-to-date

### ISSUE THREAD

**Issue by maelle** [lorenzwalthert/precommit#51]
Feature request :-)

Codemeta is a standard for metadata describing software. `codemetar` creates codemeta.json for R packages based on DESCRIPTION, README, etc. https://github.com/ropensci/codemetar

Current hook template: https://github.com/ropensci/codemetar/blob/master/inst/templates/description-codemetajson-pre-commit.sh

Could one make it a part of the default collection, if the script checked for codemeta.json existence?

As shown by #50, I am very new at all this stuff.

**Comment by lorenzwalthert** [comment]
If your feature request is to add a git commit hook that checks if the codemetar is up to date (without adding codemeta itself to this repo), I think I am open to this. The template you mention is a good starting point, we can c/p this more or less and add some tests / documentation and that would be it.

There is currently one config file that will be created with `precommit::use_precommit()`, but I think eventually we might create different templates for different use cases and you can specify the use case in the above command. Also, we could allow user-specific templates. Speed is pretty important so I think we want to avoid a situation where a lot of hooks are checking for for files we know are not present, but I think we can handle that in separate issues.

**Comment by maelle** [comment]
> If your feature request is to add a git commit hook that checks if the codemetar is up to date (without adding codemeta itself to this repo), I think I am open to this.

Yes that's my feature request!

**Comment by maelle** [comment]
I'll make a PR. I'm looking at tests, and can't find where the README hook is tested?

**Comment by lorenzwalthert** [comment]
It's not I think. Testing works only for hooks that use `Rscript` as the CONTRIBUTING.md says.

**Comment by maelle** [comment]
So I could make a PR with the hook and no test? Btw could one parameterize a hook? The codemeta.json hook would be exactly like the README one except README.Rmd -> DESCRIPTION and README.md -> codemeta.json.

**Comment by lorenzwalthert** [comment]
> The codemeta.json hook would be exactly like the README one except README.Rmd -> DESCRIPTION and README.md -> codemeta.json.

I don't think they are that similar. Because the readme hook is a bash hook. Doesn't your hook involve calling R code? I'd rather say the oxygen hook is very similar to what you do. Have a look at that one.

**Comment by maelle** [comment]
No, our current hook is really like the README one because we don't want to run write_codemeta() too often.

**Comment by lorenzwalthert** [comment]
Then don't add a test for now.

**Comment by lorenzwalthert** [comment]
Also, to filter, use the pre-comit way of filtering files (as the other hooks do) to check if the hook should be ran at all.

**Comment by maelle** [comment]
> Also, to filter, use the pre-commit way of filtering files (as the other hooks do) to check if the hook should be ran at all.

Actually I don't understand what this means, because the other hooks are R scripts. Sorry.

**Comment by lorenzwalthert** [comment]
Closed with #60.
