### ISSUE TITLE
Make updating `inst/WORDLIST` optional

### ISSUE THREAD

**Issue by TymekDev** [lorenzwalthert/precommit#510]
**Is your feature request related to a problem? Please describe.**
Make updating `inst/WORDLIST` optional.

**Describe the solution you'd like**
Add an additional flag for disabling `inst/WORDLIST` update.

https://github.com/lorenzwalthert/precommit/blob/main/inst/hooks/exported/spell-check.R#L3-L10

**Additional context**
Hi! I would like to use the spell-check hook without having overwritten anything, just throwing an error when applicable. Do you thing it makes sense to make it possible to opt-out of update functionality? If yes, then I will be happy to contribute the changes. :-)

**Comment by lorenzwalthert** [comment]
Yes, I'd be open to that change. Can you have a look at the docs of the current hook and submit a PR? Please include the option in the error message of both code paths so people get hints to either activate or de-activate it.
