### ISSUE TITLE
Allow alternative spellcheck dictionary files

### ISSUE THREAD

**Issue by jashapiro** [lorenzwalthert/precommit#528]
**Is your feature request related to a problem? Please describe.**
I have an existing CI script that does spell checking, but the file that we use for the dictionary is stored in a different location, and I would like to preserve that file structure.

**Describe the solution you'd like**
Allow an option for the `spell-check` hook to specify the dictionary file location (keeping the default as `inst/WORDLIST`)

**Describe alternatives you've considered**
Altering my workflow, but that is not ideal.

Thanks for this package, it is quite handy!

**Comment by lorenzwalthert** [comment]
Which package do you use for spell checking?

**Comment by jashapiro** [comment]
We actually use the same package, but in a github action. The only difference is that we have a different location for the dictionary file from the one here. I mocked out the minimal required changes in https://github.com/jashapiro/precommit/tree/jashapiro/wordlist-path. Just a few lines (though I also played around with message text).

**Comment by lorenzwalthert** [comment]
To me, it seems like {spelling} [requires](https://docs.ropensci.org/spelling/reference/wordlist.html?q=dict#null) the `WORDLIST` file to be in `inst/`. If that is the case, I don't think {precommit} should support customising the location of the file.

**Comment by jashapiro** [comment]
I think that is only true for spell checking a package. When spell checking individual files, as this script does, that file location is not required or used.

**Comment by lorenzwalthert** [comment]
Yes so if no dictionary file is used, you have to do a set diff operation yourself later. So it’s not part of the public API of {spelling} to provide dictionary files in arbitrary directories and that’s why we won’t support that here. Why would you not want to use the standard directory anyways?

**Comment by jashapiro** [comment]
The repository that I am using is not an R package, and does not use R as its primary language. So there is no `inst` directory at the root, and creating one is not desirable for a number of reasons. It does, however, use .Rmd files among other text files, so the {spelling} package is really the easiest way to get reliable spell checking. This of many of the analysis projects that I work on: I might have a `config` or similar at the root directory, but `inst` in a project with no installable components seems odd and unintuitive. 

The `spell_check_files()` is part of the public API, and allows providing arbitrary character strings via the `exclude` argument, which is how you have implemented it in https://github.com/lorenzwalthert/precommit/blob/main/inst/hooks/exported/spell-check.R The [changes](https://github.com/lorenzwalthert/precommit/compare/main...jashapiro:precommit:jashapiro/wordlist-path) that I am suggesting are pretty minimal, and won't affect any use within packages.

**Comment by lorenzwalthert** [comment]
Would it help if you could specify a root of the R project within your got repo? Some other hook support that for the case r package / project root don’t correspond to git root.

**Comment by jashapiro** [comment]
That might help some, but I think my idea is that this could be used for a broader range of repository types than just R projects. While this package is partly focused on setting up R projects easily, the individual hooks are more broadly useful.  I found it initially from https://pre-commit.com/hooks.html, and wanted to add it to a Nextflow workflow repository that already had spell checking enabled via CI with a different file name and location. 

I may end up writing a local hook for more extensive customization, but this seemed like a good place to start.

**Comment by lorenzwalthert** [comment]
Ok. Yes if you don’t want to live with the restriction I outlined you can write your own local or exposed hooks, it’s not that hard.
