### ISSUE TITLE
specific package not available from MRAN - what would be the next step?

### ISSUE THREAD

**Issue by danielinteractive** [lorenzwalthert/precommit#534]
Hi,

I am hitting:

```
Error: package 'GenomeInfoDbData' is not available
    In addition: Warning message:
    package 'GenomeInfoDbData' is not available from MRAN 
```

during pre-commit environment init.

What would be the recommendation?

Thanks,
cheers
Daniel

**Comment by lorenzwalthert** [comment]
There is an issue template on this repo for bugs. If you don’t follow it, it’s hard for me to provide any guidance. For your specific issue, please share at least your `.pre-commit-config.yaml`.

**Comment by lorenzwalthert** [comment]
FWIW MRAN has been discontinued and the dependency is most likely an `additonal_dependeny`. That probably would be most likely resolved with a `$ pre-commit autoupdate` or the equivalent in R (`precommit::autoupdate()`).

**Comment by danielinteractive** [comment]
Thanks @lorenzwalthert, interestingly I cannot reproduce this problem on the second system (Ubuntu), it only appeared on the Mac. Therefore closing - sorry for the noise!

**Comment by lorenzwalthert** [comment]
Welcome, feel free to re-open once it happens again on macOS, some issues are platform specific.
