### ISSUE TITLE
Failure with dev (now CRAN) roxygen2

### ISSUE THREAD

**Issue by hadley** [lorenzwalthert/precommit#535]
```
── Failure ('test-hook-roxygenize.R:168:3'): warns if there is any other warning ──
`roxygenize_with_cache(list(getwd()), dirs = dirs_R.cache("roxygenize"))` did not produce any warnings.
```

Unfortunately this wasn't flagged in our cloud checks (presumably because precommit mostly skips them in our test environment). The root cause is that roxygen2 now uses messages rather than warnings for feedback. The fix to the test might look something like this:

```R
test_that("forwards feedback from roxygen2", {
  local_edition(3)
  
  local_test_setup(git = FALSE, use_precommit = FALSE, package = TRUE)
  mockery::stub(roxygenize_with_cache, "diff_requires_run_roxygenize", TRUE)
  writeLines(
    c(
      "#' This is a title", "#'", "#' More", "#", "NULL"
    ),
    "R/blur.R"
  )

  expect_snapshot(
    roxygenize_with_cache(list(getwd()), dirs = dirs_R.cache("roxygenize"))
  )
})
```

**Comment by lorenzwalthert** [comment]
Ok. Interesting that it was not even flagged by CRAN. Anyways, thanks for letting me know, I think the fix you outlined will solve it. Will try to implement it soon.
