### ISSUE TITLE
Environment setup fails due to a hardcoded snapshot RSPM link in renv.lock

### ISSUE THREAD

**Issue by TymekDev** [lorenzwalthert/precommit#573]
**Before filing a bug**

- [x] I have installed the latest dev version of {precommit} with `remotes::install_github('lorenzwalthert/precommit')`
- [x] I have installed the latest hook revisions (update with `precommit::autoupdate()`)
- [x] I have installed the latest release of the upstream Python framework pre-comit as described under the [update instructions](https://lorenzwalthert.github.io/precommit/dev/articles/precommit.html#update).

**Describe the bug**
Currently, RSPM inside `renv.lock` uses a snapshot URL:

https://github.com/lorenzwalthert/precommit/blob/efaa00a02f26ec310ef83d45d1d0e21db73d4473/renv.lock#L4-L9

This means that packages released on CRAN after March 29th break hook environment setup. In my case the package is [`{box.linters}`](https://cran.r-project.org/package=box.linters).

<details>
<summary>Logs (click to expand)</summary>
<pre><code>[INFO] Initializing environment for https://github.com/lorenzwalthert/precommit:box.linters.
[INFO] Installing environment for https://github.com/lorenzwalthert/precommit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/bin/Rscript', '--no-save', '--no-restore', '--no-site-file', '--no-environ', '/var/folders/lh/y7zmk_td7nzfjxxqxdwhy5r40000gn/T/tmplcuw405r/script.R', 'box.linters')
return code: 1
stdout: (none)
stderr:
    Error: package 'box.linters' is not available
    In addition: Warning message:
    package 'box.linters' is not available from MRAN
    Traceback (most recent calls last):
    7: renv::install(commandArgs(trailingOnly = TRUE))
    6: retrieve(names(remotes))
    5: handler(package, renv_retrieve_impl(package))
    4: renv_retrieve_impl(package)
    3: renv_available_packages_latest(package)
    2: stopf("package '%s' is not available", package)
    1: stop(sprintf(fmt, ...), call. = call.)
    Execution halted
Check the log at /Users/tymek/.cache/pre-commit/pre-commit.log</code></pre>
</details>

**To Reproduce**
1. Use the following `.pre-commit-config.yaml`:
    ```yaml
    repos:
      - repo: https://github.com/lorenzwalthert/precommit
        rev: v0.4.2
        hooks:
          - id: roxygenize
            additional_dependencies:
              - box.linters
    ```
2. Run `pre-commit run --all-files`

**Expected behavior**
The environment gets successfully set up and the hook runs

**Comment by lorenzwalthert** [comment]
This is correctly thanks for the comprehensive issue. Will do a hook revision update soon. Technically these should be automated the the workflow broke. We chose to use these snapshot urls since they are the only way to provide access to binaries on all platforms even for when there were never versions. 

As a workaround, you can also reference the package on GitHub, in particular if the release is tagged..

**Comment by TymekDev** [comment]
I appreciate the timely response! I know first-hand all about binary fetching problems... 😖

I'll go with a tagged GitHub release, thanks for the tip!

**Comment by dylanbyc** [comment]
I am facing a similar issue, my organisation is blocking RSPM, we usually use a custom internal artifactory when installing packages. Is there a way to define custom artifactory?

**Comment by lorenzwalthert** [comment]
Not really. Easiest is to fork this repo, change `renv.lock` to include the repo you want and then refer to the fork in your `.pre-commit-config.yaml`.

**Comment by dylanbyc** [comment]
Thank you, I will implement as suggested👍

**Comment by lorenzwalthert** [comment]
Note that you'll need to push all the tags to that fork. At some point later, we might be able to support configuring the repos...
