### ISSUE TITLE
How do I wrap markdown in my .qmd files?

### ISSUE THREAD

**Issue by boxydog** [lorenzwalthert/precommit#579]
**Is your feature request related to a problem? Please describe.**
The style-files pre-commit hook version 0.4.2 is not wrapping markdown in my .qmd files.

**Describe the solution you'd like**
I want a pre-commit hook to wrap markdown in my .qmd files.

**Additional context**

What is the following diagram on the github home page:

<img width="154" alt="image" src="https://github.com/user-attachments/assets/2fcfd2f5-63bb-4574-a9ef-139a102d3f36">

I feel like that implies that markdown will be wrapped, if only I could set it, or check its setting.

**Comment by boxydog** [comment]
FYI I can see it styling the R code, so I know it's being applied to the .qmd. It's just that the markdown outside the R chunks is not being wrapped.

**Comment by lorenzwalthert** [comment]
the styler hook formats the R code, there is no styling of non-r elements supported with styler, hence, what you observe is the expected behavior . You can look for other formatting tools that support non-code formatting, like markdown formatters.

**Comment by lorenzwalthert** [comment]
Maybe you find some discussion about  in the issues.

**Comment by boxydog** [comment]
Gotcha.

So what is the "editor_options" / "markdown" / "wrap" diagram on https://github.com/lorenzwalthert/precommit for?

**Comment by lorenzwalthert** [comment]
It’s created automatically when you use RSudio visual mode I think.
