### ISSUE TITLE
style-files fails with unused arguments

### ISSUE THREAD

**Issue by deeplook** [lorenzwalthert/precommit#586]
This is likely a feature request...

I'm trying to run these pre-commit hooks on existing R code, but I get errors like this which (to me as a non-R-expert) appear to be due to the fact that the R code is not packaged and does not use `renv` (and hence there is no, `renv.lock` file):

```
style-files..............................................................Failed
- hook id: style-files
- exit code: 1

- The project is out-of-sync -- use `renv::status()` for details.
- The project is out-of-sync -- use `renv::status()` for details.
NULL
[1] "cache root set to " "styler-perm"       
Error in style(...) : unused arguments (type = "R", `NA` = NULL)
Calls: tryCatch ... <Anonymous> -> transform_files -> make_transformer -> force
Execution halted
- The project is out-of-sync -- use `renv::status()` for details.
- The project is out-of-sync -- use `renv::status()` for details.
NULL
[1] "cache root set to " "styler-perm"       
Error in style(...) : unused arguments (type = "R", `NA` = NULL)
Calls: tryCatch ... <Anonymous> -> transform_files -> make_transformer -> force
Execution halted
```

A nice solution would be to just run these hooks on plain R code without having to turn it into a full-fledged package.

**Comment by lorenzwalthert** [comment]
Please follow the issue template outlined in this repo.

**Comment by lorenzwalthert** [comment]
actually there was a loop hole and you said you don't know exactly what this is so I give you the benefit of the doubt 😀.

**Comment by lorenzwalthert** [comment]
It's a misconception that you need to use {renv} in your repo to use pre-commit, pre-commit itself uses a renv to manage the hooks, but you should not see it, since the renv is not put in your project directory. So you can use a renv or not to manage your project's dependencies, that does not matter.

I think the source of your problem is that you pass invalid arguments to the hook. Please paste your `.pre-commit-config.yaml` here.

**Comment by lorenzwalthert** [comment]
> A nice solution would be to just run these hooks on plain R code without having to turn it into a full-fledged package.

It's not a requirement that your code repo is an R package. I am not sure where you got his this impression from. If from the docs, I'd appreciate a pointer so we can move the confusion out of the way.

**Comment by lorenzwalthert** [comment]
> - The project is out-of-sync -- use `renv::status()` for details.

I can't explain these, since the renv gets installed once in pre-commit's cache and then should be frozen, so I don't see how this can get out of date except if you change installed versions yourself in this renv, or change the `renv.lock` or similar.

**Comment by deeplook** [comment]
I know that pre-commit runs the hooks inside its own dedicated environment. But for some reason it seems to cause an error on my five R files in an otherwise unstructured directory. So it was not immediately clear to me as a non-R person what it means, making me speculate I had to turn the code into a real R package, which I would not expect to be a mandatory requirement, after having used pre-commit on many Python projects before.

So here is my `.pre-commit-config.yaml` file, and sorry for not having posted it upfront:

```yaml
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3
    hooks:
      - id: style-files
        args: [--type, R]
 ```

**Comment by deeplook** [comment]
In fact I've run the hook now on a dummy (first) R project of mine (also not using `renv`) if I followed the tutorial right. You can see the same error in the respective GitHub action: https://github.com/deeplook/fibonacciPackage/actions/runs/10194682116/job/28201779778

**Comment by deeplook** [comment]
Thanks! TBH, I forgot where I got my snippet from. If I remove the arguments, the styling is indeed applied, which is great! There is just the same comments about `renv` that might (and do) confuse noob R users like me. But thanks a lot!

```
% pre-commit run --all-files   
style-files..............................................................Failed
- hook id: style-files
- files were modified by this hook

- The project is out-of-sync -- use `renv::status()` for details.
- The project is out-of-sync -- use `renv::status()` for details.
NULL
[1] "cache root set to " "styler-perm"       
Styling  1  files:
 R/fibonacci.R ℹ 
────────────────────────────────────────
Status  Count   Legend 
✔       0       File unchanged.
ℹ       1       File changed.
✖       0       Styling threw an error.
────────────────────────────────────────
Please review the changes carefully!

% pre-commit run --all-files
style-files..............................................................Passed
```

**Comment by lorenzwalthert** [comment]
Great. You can force a re-installation with with `pre-commit clean` and then install the hooks again. Does tie problem persist on that case?

**Comment by deeplook** [comment]
Unfortunately, that doesn't help.

**Comment by lorenzwalthert** [comment]
I can reproduce this, seems like a new change in {renv} checks now if the packages are actually used or not, and then they are market as not used, since we don't use standard {renv} mechanism. I guess we can just ignore this for now.
