### ISSUE TITLE
Problem with pkgdown hook on pull requests

### ISSUE THREAD

**Issue by pschloss** [lorenzwalthert/precommit#590]
**Before filing a bug**

- [x] I have installed the latest dev version of {precommit} with `remotes::install_github('lorenzwalthert/precommit')`
- [x] I have installed the latest hook revisions (update with `precommit::autoupdate()`)
- [x] I have installed the latest release of the upstream Python framework pre-comit as described under the [update instructions](https://lorenzwalthert.github.io/precommit/dev/articles/precommit.html#update).

**Describe the bug**
When I try to do a pull request using the default configuration yaml file it fails on the pkgdown hook 

```
pkgdown..................................................................Failed
- hook id: pkgdown
- exit code: 1

Error in loadNamespace(x) : there is no package called ‘pkgdown’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
Error in loadNamespace(x) : there is no package called ‘pkgdown’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
Error in loadNamespace(x) : there is no package called ‘pkgdown’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

**To Reproduce**
Using default output from `precommit::use_precommit(ci = "gha")` on my package, which does not use `pkgdown` as a dependency

**Expected behavior**
I would expect it to pass this pre-commit hook test

**Additional context**

- My operating system is: Mac OS X 14.6.1
- [ ] My project uses {renv}.
- [ ] the output of `packageVersion('renv')`

**Comment by lorenzwalthert** [comment]
Thanks. As per the [docs](https://lorenzwalthert.github.io/precommit/articles/available-hooks.html#pkgdown), this hook used the global R library as it is primarily thought to be used locally. You can skip it on CI with the respective entry in `.pre-commit.yaml` as per the pre-commit.ci or by setting the SKIP env variable.

**Comment by lorenzwalthert** [comment]
Or you install this pclage in your ci run manually.

**Comment by lorenzwalthert** [comment]
That works for pre-commit.ci only. You need to handle skipping manually for GitHub Actions.
