### ISSUE TITLE
Option to increase max line length from 80 to 120

### ISSUE THREAD

**Issue by j-beresford** [lorenzwalthert/precommit#599]
First off, thanks so much for making this available!

Question: Taking the default pre-commit-config.yml as default, is there an option for increasing the max line-length under lintr? If not, would it be possible to get one added?

At my firm, we have these annoyingly long file paths (unchangeable by me!) and they make the default line-length pretty unworkable. 

Thanks again!

**Comment by lorenzwalthert** [comment]
Yes, it’s a lintr setting that precommit looks up. Happy to review a PR if Tue docs are not clear.
