### ISSUE TITLE
add hook to verify that you inflate your file when developping R package with {fusen}

### ISSUE THREAD

**Issue by LBeaulaton** [lorenzwalthert/precommit#601]
**Is your feature request related to a problem? Please describe.**
When developing R package with [{fusen}](https://github.com/ThinkR-open/fusen) you can forget to inflate your file before committing.

**Describe the solution you'd like**
When committing check that your .Rmd file have been inflated and thus that your corresponding .R file are up-to-date.

**Comment by lorenzwalthert** [comment]
Thanks for the suggestion. Is there a command from the {fusen} package you'd like to call or how would you check that?

**Comment by LBeaulaton** [comment]
Thanks for taking my suggestion into account.
I think that these two vignettes may help: [Draw a tree of your package files and functions](https://thinkr-open.github.io/fusen/articles/draw-a-tree-of-your-package-files-and-functions.html) and [Register files in config](https://thinkr-open.github.io/fusen/articles/register-files-in-config.html).

Thinking further, several checks may be implemented:
1. *Check for any unregistered file* using [`fusen::check_not_registered_files`](https://thinkr-open.github.io/fusen/reference/check_not_registered_files.html) function. If this function return a non `NULL` value this means that unregistered files exist and thus exit code should be 1.
2. *Check for flat files never inflated*.  Internal function [`pre_inflate_all_diagnosis`](https://github.com/ThinkR-open/fusen/blob/main/R/inflate_all_utils.R) produces a tibble with the status (`type` column) of each flat files. If there is any flat file with `type == "cli::cli_alert_danger"`  exit code should be 1.
3. *Check for chunks in flat files never inflated* using [`fusen::inflate_all_no_check`](https://thinkr-open.github.io/fusen/reference/inflate_all.html) function. If this creates new R files some Chunks have never been inflated  and thus exit code should be 1.

**Comment by lorenzwalthert** [comment]
Ok I am sorry I don't have time to read that docs or understand how the package works. I don't really want to add the fusen dependency here and so many different hooks (from a package that is not used as widely as most of the other hooks here) so I suggest you host your own hook repo as explained in https://pre-commit.com/#r. Just create an R package, add {renv} and a `.pre-commit-hooks.yaml` and reference the R scripts that should run as hook.

**Comment by LBeaulaton** [comment]
Thanks for the instruction. I will try to do that when time available and when done will report here.
