### ISSUE TITLE
Could the vignette about available hooks be generated from .pre-commit-hooks.yaml.?

### ISSUE THREAD

**Issue by maelle** [lorenzwalthert/precommit#63]
As a table for instance that'd parse the file?

**Comment by lorenzwalthert** [comment]
Yes, I think we could do that. We should take as input:

- the precommit config file.
- some other file that describes all other attributes of the hooks, preferably in yaml too (I am not sure if pre-commit allows us to add new fields to the config file).

We could also try to add the information to the `.pre-commit-config.yaml` file. If it does not produce errors at commit time or while other hooks are running, I think it might even preferred. 

I am not sure if we prefer tables. We can also use the  R package https://github.com/kiernann/gluedown to generate markdown in R chunks in the  vignette and set `output = "asis"` (if I remember the Rmarkdown options correctly).

I am open to PRs here.


The same is probably also possible with the argument vignette.

**Comment by lorenzwalthert** [comment]
If all current formatting with links etc. is possible in tabular format, you are probably right that this would be better than the current bullets.

**Comment by maelle** [comment]
Here's what I have at the moment.

``` r
info <- yaml::read_yaml("/home/maelle/Documents/ropensci/precommit/.pre-commit-hooks.yaml")

info_df <- data.frame(
  id = unlist(
    lapply(
      info, "[", "id"
    )
  ),
  description = unlist(
  lapply(
    info, "[", "description"
    )
  )
)

knitr::kable(info_df)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">id</th>
<th style="text-align: left;">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">roxygenize</td>
<td style="text-align: left;">run roxygen2::roxygenize()</td>
</tr>
<tr class="even">
<td style="text-align: left;">use-tidy-description</td>
<td style="text-align: left;">run usethis::use_tidy_description()</td>
</tr>
<tr class="odd">
<td style="text-align: left;">style-files</td>
<td style="text-align: left;">style files with styler</td>
</tr>
<tr class="even">
<td style="text-align: left;">no-browser-statement</td>
<td style="text-align: left;">check if a .R file contains a <code>browser()</code> statement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">parsable-R</td>
<td style="text-align: left;">check if a .R file is parsable</td>
</tr>
<tr class="even">
<td style="text-align: left;">readme-rmd-rendered</td>
<td style="text-align: left;">make sure README.Rmd hasn’t been edited more recently than README.md</td>
</tr>
<tr class="odd">
<td style="text-align: left;">codemeta-description-updated</td>
<td style="text-align: left;">make sure codemeta.json is in sync with DESCRIPTION. It should be run after use-tidy-description.</td>
</tr>
<tr class="even">
<td style="text-align: left;">spell-check</td>
<td style="text-align: left;">perform a spell check with spelling::spell_check_files()</td>
</tr>
<tr class="odd">
<td style="text-align: left;">deps-in-desc</td>
<td style="text-align: left;">Check if dependencies that can be parsed from code are in DESCRIPTION.</td>
</tr>
<tr class="even">
<td style="text-align: left;">lintr</td>
<td style="text-align: left;">check if a .R file is lint free (using lintr)</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Are you saying more info could be added to the same YAML? It'd be great because it'd be more transparent than having info about each hook split in two places.

**Comment by lorenzwalthert** [comment]
Thanks! Looks good. Do you think we should merge the vignette on additional arguments with the available hooks vignette?

**Comment by maelle** [comment]
Yes, all info in one place sounds good. Is it possible to use html details tag in a table? If so it'd be a good way to keep the table compact at first glance.

**Comment by lorenzwalthert** [comment]
I don't understand the question, sorry.

**Comment by maelle** [comment]
Look I've added a test below in the first cell. The column with arguments could have details tags so one would click to see arguments. I think the `details` package could help.
<table>
<thead>
<tr class="header">
<th style="text-align: left;">id</th>
<th style="text-align: left;">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><details><summary>arguments</summary>blablabla</details>roxygenize</td>
<td style="text-align: left;">run roxygen2::roxygenize()</td>
</tr>
<tr class="even">
<td style="text-align: left;">use-tidy-description</td>
<td style="text-align: left;">run usethis::use_tidy_description()</td>
</tr>
<tr class="odd">
<td style="text-align: left;">style-files</td>
<td style="text-align: left;">style files with styler</td>
</tr>
<tr class="even">
<td style="text-align: left;">no-browser-statement</td>
<td style="text-align: left;">check if a .R file contains a <code>browser()</code> statement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">parsable-R</td>
<td style="text-align: left;">check if a .R file is parsable</td>
</tr>
<tr class="even">
<td style="text-align: left;">readme-rmd-rendered</td>
<td style="text-align: left;">make sure README.Rmd hasn’t been edited more recently than README.md</td>
</tr>
<tr class="odd">
<td style="text-align: left;">codemeta-description-updated</td>
<td style="text-align: left;">make sure codemeta.json is in sync with DESCRIPTION. It should be run after use-tidy-description.</td>
</tr>
<tr class="even">
<td style="text-align: left;">spell-check</td>
<td style="text-align: left;">perform a spell check with spelling::spell_check_files()</td>
</tr>
<tr class="odd">
<td style="text-align: left;">deps-in-desc</td>
<td style="text-align: left;">Check if dependencies that can be parsed from code are in DESCRIPTION.</td>
</tr>
<tr class="even">
<td style="text-align: left;">lintr</td>
<td style="text-align: left;">check if a .R file is lint free (using lintr)</td>
</tr>
</tbody>
</table>

**Comment by lorenzwalthert** [comment]
That's pretty cool. I assume this would also work in the {pkgdown} html page?

**Comment by maelle** [comment]
I suppose so thanks to `details`, but my problem is where the info would live (can you add any field to the YAML without breaking it for precommit purposes)?

**Comment by lorenzwalthert** [comment]
We could create a `.pre-commit-docs.yaml` and link via id: 
```yaml
-   id: roxygenize
-   id: use-tidy-description
-   id: style-files
    args: 
    - --style_pkg=<package name >, defaulting to styler
    - --style_fun=<tidyverse_style>, defaulting to tidyverse_style
-   id: no-browser-statement
-   id: parsable-R
-   id: readme-rmd-rendered
-   id: codemeta-description-updated
-   id: spell-check 
-   id: deps-in-desc
-   id: lintr
```

An then do something like this:

``` r
library(magrittr)
library(rlang)
#> 
#> Attaching package: 'rlang'
#> The following object is masked from 'package:magrittr':
#> 
#>     set_names
hooks <- yaml::read_yaml("~/git/precommit/.pre-commit-hooks.yaml")
details <- yaml::read_yaml("~/git/precommit/.pre-commit-docs.yaml")

hooks_df <- data.frame(
  id = unlist(
    lapply(
      hooks, "[", "id"
    )
  ),
  description = unlist(
    lapply(
      hooks, "[", "description"
    )
  )
)

details_df <- purrr::map_dfr(details, 
    ~ tibble::tibble(id = .x$id, args = paste0(" ", .x$args %||% ""))
) %>%
  dplyr::group_by(.data$id) %>%
  dplyr::summarize(args = paste0(.data$args, collapse = " "))

as_details <- function(args) {
  purrr::map_if(
    args, args != " ",
    ~details::details(.x, lang = NULL, output = "character") %>%
      gsub("\\n", "", .)
  )
}


details_df %>%
  dplyr::full_join(hooks_df) %>%
  dplyr::mutate(
    args = as_details(.data$args),
    description = paste0(
      .data$description, 
      args
    )
  ) %>% # View()
  dplyr::select(-.data$args) %>%
  knitr::kable(format = "markdown")
#> Joining, by = "id"
#> Warning: Column `id` joining character vector and factor, coercing into
#> character vector
```
|id                           |description                                                                                                                                                           |
|:----------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|codemeta-description-updated |make sure codemeta.json is in sync with DESCRIPTION                                                                                                                   |
|deps-in-desc                 |Check if dependencies that can be parsed from code are in DESCRIPTION.                                                                                                |
|lintr                        |check if a .R file is lint free (using lintr)                                                                                                                         |
|no-browser-statement         |check if a .R file contains a `browser()` statement                                                                                                                   |
|parsable-R                   |check if a .R file is parsable                                                                                                                                        |
|readme-rmd-rendered          |make sure README.Rmd hasn't been edited more recently than README.md                                                                                                  |
|roxygenize                   |run roxygen2::roxygenize()                                                                                                                                            |
|spell-check                  |perform a spell check with spelling::spell_check_files()                                                                                                              |
|style-files                  |style files with styler<details closed> --style_pkg=<package name >, defaulting to styler  --style_fun=<tidyverse_style>, defaulting to tidyverse_style</details><br> |
|use-tidy-description         |run usethis::use_tidy_description()                                                                                                                                   |
<sup>Created on 2020-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maelle** [comment]
Or details in a third column? It looks good in any case!

**Comment by lorenzwalthert** [comment]
Actually I think we should not use a table anyways, I just unified two vignettes in #109.
