### ISSUE TITLE
"deps-in-desc" hook should ignore ::: calls

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#64]
In our tests we have something like

```
mlr:::<function>
```

and precommit hook "deps-in-desc" errors because we haven't got package "mlr" in our DESC file (for pkg mlr).

I'd consider this as a false-positive here. Is there some way to omit checks for this hook on the pkg name of the current project?

(Maybe accounting for the triple doublecolons is a separate issue)

**Comment by lorenzwalthert** [comment]
I am not sure we should ignore `:::` in general, maybe it could be optional. In general, I agree though that within a package, the package namespace itself should be ignored. We could derive the name of the current package from `DESCRIPTION` and ignore it. What do you think?

**Comment by pat-s** [comment]
> I am not sure we should ignore ::: in general, maybe it could be optional. 

I am not sure if this is allowed on CRAN right now (I think its not?). If it is not, I'd say it is valid to flag it. 
However, the problem occurred in our test files and there one might have more often `:::` calls (I think there is more freedom in tests than in `R/`). 

Flagging ::: in the hook puts kind of a weight to it, like "this is really bad, you are not allowed to do this or I will fail".

But idk really what the best approach regarding ::: would be.

**Comment by lorenzwalthert** [comment]
Well with *optional*, I meant it could be configured by the user as a [hook argument](https://lorenzwalthert.github.io/precommit/articles/hook-arguments.html). As you said, `:::` is not allowed in general on CRAN I believe.

But can we simply agree for a first step to ignore the package namespace? Because that would solve the `mlr:::` problem in the package mlr.

**Comment by lorenzwalthert** [comment]
@pat-s can you test this? `precommit::autoupdate()` -> `v0.0.0.9026`, and commit a file? In your config file, set the flag `--allow_private_imports` to allow functions from other packages to be called with `:::`.

**Comment by pat-s** [comment]
Like this? (just to confirm before I commit the yaml)

```
    -   id: deps-in-desc
        args: ['--allow_private_imports'] # skips checking <pkg>:::<fun> imports
```

Thanks for the quick fix!

**Comment by lorenzwalthert** [comment]
I think the quotes must be omitted!

**Comment by lorenzwalthert** [comment]
But the option only limits imported private function calls. In mlr, you can still do `mlr:::xxx()` even without setting this option.

**Comment by lorenzwalthert** [comment]
Also see https://lorenzwalthert.github.io/precommit/articles/hook-arguments.html, maybe we can state that quotes should be omitted there explicitly.

**Comment by pat-s** [comment]
I used quotes because there is this entry in the YML which uses quotes:

```
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
```

Maybe you could allow both notations?

> In mlr, you can still do mlr:::xxx() even without setting this option.

Thanks. I haven't yet wrapped my head around whether I want to allow for this or not :smile:

**Comment by lorenzwalthert** [comment]
Ok, maybe we should adapt that example then. Not sure it even works currently then?!. I think the quote topic should be handled by the upstream repo. And all their examples are without quotes, plus I vaguely remember I had issues with this. https://pre-commit.com/#passing-arguments-to-hooks

**Comment by pat-s** [comment]
> Ok, maybe we should adapt that example then. Not sure it even works currently then?!. 

Idk, I haven't commited large files lately.

Also hook revision 9026 solves this issue here :)
