### ISSUE TITLE
Don't throw an error when not using RStudio

### ISSUE THREAD

**Issue by michaelquinn32** [lorenzwalthert/precommit#79]
Calls to precommit::use_precommit() will throw an error if the user doesn't use RStudio.

**Comment by lorenzwalthert** [comment]
Thanks. Can we in the future please provide a reprex? I think your solution works, but conceptually, calling a function to open a file given that this is not possible should result in an error. Calling that function indirectly, e.g. via `use_precommit()` should not. So my suggestion: give a new default to `open` in `use_precommit()`, namely `rstudioapi::isAvailable()`. This should prevent the primary problem you are after.

**Comment by lorenzwalthert** [comment]
Wanna adapt #77 according to my suggestions? Also, then you could delete the code to resolve #78 (which has merge conflicts by now) until we decided on that and we could merge #77 soon.
