### ISSUE TITLE
Add usethis version requirement

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#81]
I get the following with _usethis_ v1.4.0
Not sure which minimal version is needed, just FYI :)

```
precommit::install_precommit()
Error: 'ui_info' is not an exported object from 'namespace:usethis'
```

**Comment by lorenzwalthert** [comment]
Ok, I think we need 1.5.
``` r
namespaces::find_first_release('usethis', 'ui_done')
#> [1] "1.5.0"
```

<sup>Created on 2019-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pat-s** [comment]
Neat function: `namespaces::find_first_release()`!
