### ISSUE TITLE
Hook request: Check for 404 links in README

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#83]
I just came across a few dead links in a README and was wondering if this could be catched via pre-commit hook :)

**Comment by lorenzwalthert** [comment]
Great idea. What’s really awesome about pre-commit is that it supports many languages and it handles all dependencies for supported languages. So my approach would be 

- to look for an available hook that does this. I [could not find one](https://pre-commit.com/hooks.html). 
- look for a tool that does this, written in any of the [supported languages](https://pre-commit.com/#supported-languages). I found this one in node: https://github.com/tcort/markdown-link-check and it seems under active development.

We can find instructions [here](https://pre-commit.com/#node) on how to add a hook and potentially also check the existing node repo https://github.com/pre-commit/mirrors-eslint to get a feel for it. Are you interested in contributing?

**Comment by lorenzwalthert** [comment]
Try this adding this to your `.pre-commit-config.yaml`:

```yaml
Add this to your `.pre-commit-config.yaml`:

    -   repo: https://github.com/lorenzwalthert/precommit-markdown-link-check
        rev: v0.0.0.9002  # Use the sha / tag you want to point at
        hooks:
        -   id: markdown-link-check
```

See https://github.com/lorenzwalthert/precommit-markdown-link-check. Note that it can only check md or rmd READMEs as of now because of tcort/markdown-link-check#78.

**Comment by lorenzwalthert** [comment]
Should we close this as resolved?

**Comment by pat-s** [comment]
Sorry, forgot to reply. Didn't I do that somewhere else? Worked for me and I like it a lot!

I think you can def link it even if #78 would be a nice addition.

**Comment by pat-s** [comment]
@lorenzwalthert 

The new [r-lib/urlchecker](https://github.com/r-lib/urlchecker) could be a great hook :) Takes a while though - maybe in combination with caching?
