### ISSUE TITLE
Can 'docopt' be installed when this package is installed?

### ISSUE THREAD

**Issue by DaveParr** [lorenzwalthert/precommit#88]
Thanks, this is actually just what I was looking for.

Ran into a small bump on install: 

I ran:

```
remotes::install_github("lorenzwalthert/precommit")
```

then added this to a pre-existing `.pre-commit-config.yaml` (I'm actually using this to extend a project that has both R and Python and is already also using pre-commit)
```
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.0.0.9027
    hooks: 
    -   id: style-files
```

Which on run of `pre-commit` from the terminal gave:
```
style-files..............................................................Failed
hookid: style-files

Error in loadNamespace(name) : there is no package called ‘docopt’
```

I was easily able to correct for this after running  `install.packages("docopt")`, ~but is it possible to add this to the `imports` or similar so it's already sorted?~ but it appears it's already in the imports section. Maybe it needs to be in `depends`?

**Comment by lorenzwalthert** [comment]
That's indeed strange. I thought {remotes} would also install all dependencies. No, I think `Imports:` is right, I don't think `Depends:` is the right field for almost any dependency.

**Comment by DaveParr** [comment]
Sure, no problem. Close if you think best, thanks for getting back to me.

**Comment by scottgigante** [comment]
I don't think it's a problem with `Depends` vs `Imports`, but this is definitely a problem. 
```
 style-files..............................................................Failed
- hook id: style-files
- exit code: 1

Error: Error in loadNamespace(name) : there is no package called ‘docopt’
```
https://github.com/singlecellopenproblems/SingleCellOpenProblems/runs/2042401231?check_suite_focus=true#step:7:60

**Comment by scottgigante** [comment]
I just saw this cautionary note in the docs: https://lorenzwalthert.github.io/precommit/index.html#caution

I think the right solution here is to give a clearer error message that dependencies should be installed manually, and list the relevant deps for each hook.

**Comment by lorenzwalthert** [comment]
Thanks. We’ll hopefully get R support in pre-coming soon in https://github.com/pre-commit/pre-commit/pull/1799 so o hope you understand I don’t bother to add better error messages for this case.
