### ISSUE TITLE
Allow installation without conda, or explain the dependency

### ISSUE THREAD

**Issue by dfrankow** [lorenzwalthert/precommit#94]
I am delighted to find this project. Thanks for all your work.

I don't use conda much, or at all. I understand it at a high level (yet another python package manager), but not in the details. It seems like an extensive new beast to learn. I'd rather avoid it. Sounds like [you have reason to avoid it as well](https://github.com/lorenzwalthert/precommit/issues/49#issuecomment-559162217).

Is there a way to install these R pre-commit hooks without conda?

If not, could you explain the nature of the dependency a bit (so I can come to terms with it), and suggest the easiest way to adopt these pre-commit hooks if I don't know conda?

Thanks for your attention.

**Comment by lorenzwalthert** [comment]
Welcome, glad to hear you find it useful. From the README:

> If you don’t want to use conda, see vignette[`("manual-installation")`](https://lorenzwalthert.github.io/precommit/articles/manual-installation.html) for alternative installation methods.

Let me know if you have further questions.

**Comment by dfrankow** [comment]
Thank you!

My apologies, I missed that sentence.

**Comment by dfrankow** [comment]
How does this work: _"set the R option precommit.executable to the path where the pre-commit executable lives."_? Where exactly? In the pre-commit yaml somewhere? In ~/.Rprofile? Somewhere else? I didn't do this.

Below are a few more comments, only for your information (no action needed).

I have pre-commit installed already. I added the block from [here](https://lorenzwalthert.github.io/precommit/articles/manual-installation.html) to my .pre-commit-config.yaml. Not sure how to tell if the repo version is correct.

I ran `pre-commit run --files util.R` and three hooks fail:

```
hookid: style-files

Error in packageVersion("styler") : package ‘styler’ not found
```

So I'll install styler.

```
hookid: deps-in-desc

Error: No root directory found in /Users/dan/work/scrimmage/analytics or its parent directories. Root criterion: contains a file `DESCRIPTION` with contents matching `^Package: `
Execution halted
```

Since I don't have a package, maybe I don't want deps-in-desc.

```
hookid: lintr

Error: File analysis/customer_decks/util.R is not lint free
```

Looks like I have lint.

**Comment by lorenzwalthert** [comment]
Go to your terminal and type `$where pre-commit`. This gives you the path to the executable. Set this R option in your `.Rprofile`. Well done to install styler and disable the hooks aimed for package developers. Now run `pre-commit autoupdate` to make sure you get a newer version of the hooks than `v0.0.0.9016` and you should see a more helpful error message.

**Comment by lorenzwalthert** [comment]
I am adapting the vignette based on your feedback in #95. This is really valuable, because I think a few things went wrong / were unclear for you. Thanks for the feedback.

**Comment by dfrankow** [comment]
Thanks! Glad my feedback was useful. Everything is working for me.

For whatever reason, I did not have to set precommit.executable anywhere. Maybe it finds it in the path.

**Comment by lorenzwalthert** [comment]
@ dfrankow ok interesting. Which installation method did you choose?

**Comment by dfrankow** [comment]
Manual.

I don't plan to use conda.

**Comment by lorenzwalthert** [comment]
yes but which command did you run to invoke the [installation process](https://pre-commit.com/#installation)?

**Comment by dfrankow** [comment]
Er .. I installed pre-commit awhile ago. Years? I forgot how I got it. Maybe `sudo pip3 install precommit` ?

```
$ pip3 freeze | grep commit
pre-commit==1.14.4
```

**Comment by dfrankow** [comment]
Yet it's owned by me (not root), so maybe `pip3 install precommit`?

**Comment by lorenzwalthert** [comment]
ok, thanks.

**Comment by dfrankow** [comment]
Whoops, from the page it's with a dash: `pip3 install pre-commit`.

**Comment by dfrankow** [comment]
Also: it's in /usr/local/bin/pre-commit, and running system("pre-commit -h") in R returns the help, so it must be using the path.

**Comment by lorenzwalthert** [comment]
Yes but I am confused because I think with the current implementation, `{precommit}` is not checking your path, so it will cause problems downstream with some commands. What do these commands return?
```r
precommit:::path_derive_precommit_exec()
precommit::autoupdate() # I expect this to fail
```

**Comment by lorenzwalthert** [comment]
We should probably consider checking the path for the executable too, this would make linking redundant if the executable is on the PATH (the one R accesses, might be a bit different than the one you access in bash).

**Comment by dfrankow** [comment]
From Rstudio:

```
> precommit:::path_derive_precommit_exec()
[1] ""
> precommit::autoupdate()
Error in file(file, "rt", encoding = fileEncoding) : 
  cannot open the connection
In addition: Warning message:
In file(file, "rt", encoding = fileEncoding) :
  cannot open file '.pre-commit-config.yaml': No such file or directory
```

Same from the command line (with Rscript).

Yet the pre-commit hooks are working like a charm. :)

**Comment by lorenzwalthert** [comment]
Ok, thanks. The reason why they work is that they are actually independent of the R package `{precommit}`. See also https://lorenzwalthert.github.io/precommit/articles/FAQ.html.

**Comment by dfrankow** [comment]
Your genius makes me happy.

**Comment by lorenzwalthert** [comment]
@dfrankow can you 
```r
remotes::install_github('lorenzwalthert/precommit')
```

Restart R and run the above commands again?

**Comment by dfrankow** [comment]
```
> precommit:::path_derive_precommit_exec()
[1] "/usr/local/bin/pre-commit"
> precommit::autoupdate()
Updating https://github.com/pre-commit/pre-commit-hooks ... already up to date.
Updating https://github.com/lorenzwalthert/precommit ... already up to date.
✔ Ran `pre-commit autoupdate` to get the latest version of the hooks.
```

Seems to be happier than it was before.

Note I was happy before, I'm happy now. Best wishes.

**Comment by lorenzwalthert** [comment]
Great. Now I am also happy because executables on the PATH are found  😊
